### ISSUE TITLE
Improve “discard changes” dialog

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#10]
When closing an unsaved file, the dialog reads:

> Editor
> Text has been modified, do you want to discard it?
> [CANCEL] [OK]

I suggest to change this dialog to make it easier to read and answer.

Variant A:

> Discard changes?
> You have unsaved changes. Do you want to close the file and discard your changes?
> [CANCEL] [DISCARD CHANGES]

Variant B:

> Save changes?
> You have unsaved changes. Please choose whether to discard them or save them to the file.
> [CANCEL] [DISCARD] [SAVE]

For more info:

https://material.io/guidelines/components/dialogs.html#dialogs-alerts

**Comment by billthefarmer** [comment]
Ok, I will look at that.
