### ISSUE TITLE
Improve appearance in F-Droid

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [billthefarmer/editor#101]
I will suggest to improve the appearance of the app in F-Droid.

Line breaks should get fixed and a header image can get added.

![2020_02_27_15_11_08](https://user-images.githubusercontent.com/11881073/75453237-e79a9480-5973-11ea-899a-5c4f2cdc0208.jpg)

**Comment by billthefarmer** [comment]
It's got one, your copy of Fdroid hasn't loaded it for some reason.

![Screenshot_20200227-141758 1](https://user-images.githubusercontent.com/3448386/75453606-11e85400-596c-11ea-9296-fd2751127f19.png)

**Comment by Tobias-B-Besemer** [comment]
Guess you have some line breaks and I think they should get removed/converted.
E.g. second line between "standalone" and "or".

**Comment by Tobias-B-Besemer** [comment]
Guess you have some line breaks and I think they should get removed/converted.
E.g. second line between "standalone" and "or".

**Comment by billthefarmer** [comment]
Well, according to the docs, you can use HTML. I shall try that and see if it works.
