### ISSUE TITLE
[Feature request] Add a replace feature

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [billthefarmer/editor#104]
This feature would allow the user gain possibility to replace any word in the app.

**Comment by billthefarmer** [comment]
This is limited by the built in copy/paste functionality. One way to do this is to select and copy the replacement text, then search for the text you want replaced and select it, then paste the replacement text.

**Comment by KrasnayaPloshchad** [comment]
So you can create a separate menu item and interface to do that, and you can also implement additional feature as Replace All.

**Comment by billthefarmer** [comment]
This is supposed to be a simple text editor. I have implemented the search function so that you can do search and replace as I explained above.
