### ISSUE TITLE
Editor not shown in LineageOS file manager under "Open with"

### ISSUE THREAD

**Issue by anonimno1** [billthefarmer/editor#105]
Hi,

just installed the app from F-Droid.
If I create a .txt file, then when tapping on it in the file manager the action to open in editor comes up. Great.
If I try to open an .org file (which is also basicaly a txt) then the file manager doesn't offer the Editor as an option. On the other hand, if I user the file Browser from the editor itself the .org is opened without a problem.
Can you associate Editor also with other data types, that are also basicaly txt?
Or implement rhe Editor to show up in the Sharing menu? Then if the file is not readable just end the app or show "Not supported."

Regards,

anonimno

**Comment by billthefarmer** [comment]
File association is done by android using mime types. Editor advertises editing any sort of text file, but it is down to android to decide what is a text file. See #74, #60, #45. I added the built in file picker because of the inconsistencies of all the file managers out there.

**Comment by anonimno1** [comment]
Ok, understood!
