### ISSUE TITLE
Autosave default does not reflect Android expectations, leading to lost data

### ISSUE THREAD

**Issue by chrysn** [billthefarmer/editor#106]
The default setting of not autosaving works contrary to users' expectations that "When I enter data, it doesn't simply get lost" -- when the app gets swiped away in the task list or the phone reboots, hours of text editing can be lost without a way to undo. This is contrary to the expectations of Android users where even 160-character SMS are automatically saved as drafts.

This could be resolved either by making autosave the default, or by automatically saving the text to a per-app location so it gets restored when the app is next opened however it was closed first.

Discarding data should always be at least a confirmed choice, and preferably undoable.

**Comment by billthefarmer** [comment]
This is a simple text editor, as advertised, not intended for editing large files or editing over an extended period of time. If you want autosaving, select the autosave option. The app will prompt if a user action would cause data loss, such as opening another file or touching the back button. However actions outside the control of the app by android or the user will defeat this.

**Comment by chrysn** [comment]
This is not necessarily about essays; in this particular case it was about taking notes about summaries and page numbers from interesting items in a stack of recipies. Sure, it's not much data, but doing it all over again still takes time.

Preserving state when going to the background is one of the core Android app quality items ([FN-S2](https://developer.android.com/docs/quality-guidelines/core-app-quality#FN-S2)), and users grew to expect that from the most basic phone interactions. Admittedly, rebooting and swiping an app out of the task list are not listed explicitly in the tests related to that functionality, but the example the default apps like SMS composition set an example. The activity reference documentation [.

Autosave is slightly distinct from this – if it is always-on, FN-S2 is trivially implemented, but when it is not, there is app state that'd be lost on
