### ISSUE TITLE
1.46+ breaks functionality with + icon

### ISSUE THREAD

**Issue by cubetronic** [billthefarmer/editor#107]
i've been using editor daily for years. i tried to get used to the new `+` icon in versions 1.46+ for new files, but it's annoying.

i know you needed to add a way to add new files, but i think that should be done under the menu. i don't add files often - very rarely, in fact - but i switch between files frequently.

i also appreciate how the + icon is similar to firefox, but editor and firefox are very different apps. i do open new tabs in firefox all day, but i don't create new text documents all day in editor. i constantly need to switch back and forth between just a few different text files.

so now, with 1.46+, i have to open the menu and tap open and select a file, whereas with 1.45-, i just tapped the folder, and tapped the file.

i'll be using 1.45 from here on out unless you restore the normal functionality in a future release.

thanks for the app.

p.s. if you want to work on a new feature, there are a ton of file types that i think should be openable in editor, like .sh, .lua, and tons of code and other things that are just text that android just won't open. i've had to change the filename, edit, change back, test, repeat. it's unfair (android is a bad OS) i can't just choose what app i want to use to open a file, so.. yeah.. i recommend associating a ton of filetypes, perhaps optionally, who knows.

**Comment by billthefarmer** [comment]
The new button is in response to a user request &ndash; #100. It's consistent with other editors and conforms with guidelines. Android classifies files according to mime type. The app file picker will open any file that android doesn't think is a media file and isn't too large. What happens with the various file managers out there varies.
