### ISSUE TITLE
missing SAF file access, to reach termux files

### ISSUE THREAD

**Issue by cauerego** [billthefarmer/editor#112]
starting in android 11, there won't be any other better way!

perhaps you can get inspired by unpopular music player. 😘

**Comment by billthefarmer** [comment]
So I looked it up, as you do, and found this - https://www.xda-developers.com/android-q-storage-access-framework-scoped-storage, note the comments. I had already decided not to increase the target API version of my apps beyond 28, unless forced to, because they have deprecated the whole preferences API. You are supposed to use AndroidX, which is full of dependencies, which then adds a whole load of unnecessary bloated garbage to your app. As I don't support Google by using their app store, they can keep their 'scoped storage'.

**Comment by cauerego** [comment]
dam it!

sorry, i didn't know that much...

to me it was just an upgrade being embraced, since termux seem to be adopting it...

looks like i'll have to keep using vim. 😣😒

hope this will be reversed before 11 final release!

what's android x?

**Comment by billthefarmer** [comment]
AndroidX is the support library - https://developer.android.com/jetpack/androidx.

**Comment by cauerego** [comment]
thanks for your support! truly remarkable!! 😁😘

i'll try to come back here and report further how i ended up managing my termux files...

there must be some way!

**Comment by billthefarmer** [comment]
I had a look at Termux and noticed it makes use of symbolic links to access the shared storage. I couldn't make symbolic links work when I tried, but in theory you could make a link from shared storage into the user part of Termux private storage, change permissions, then you could use any 'normal' android app on Termux files. In theory.

**Comment by cauerego** [comment]
yes, that works up to android 10. but they seem to have given up on it for the 11. i can't find where i read more about this, but it was directly from the devs and related to this https://wiki.termux.com/wiki/Internal_and_external_storage

unless you mean something else... i got a bit confused there! 🤣

**Comment by cauerego** [comment]
well, some great news!

https://github.com/zhanghai/MaterialFiles have saf (i already knew that) and when trying to simply open the file through it, it works! (i didn't know that)

only with jota editor (my favourite still *) and yours. i've tried markor, ted and a few others, they can't open the file.

jota says they are at `content://com.termux.documents/tree/%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fhome/document/%2Fdata%2Fdata%2Fcom.termux%2Ffiles%2Fhome%2Fweb%2Fahoxus%2Fahoxus.github.io%2Fsanflowers.md
utf-8/LF (for Linux/Android)`

(i'll leave the full path there for full reference)

meanwhile your editor says:

`/data/data/com.termux/files/home/web/ahoxus/ahoxus.github.io/sanflowers.md`

i could only read it fully by using "universal copy app" (another favourite of mine).

\* reason i still prefer jota: highlight works there, regex search... not much else, i guess. 😏
