### ISSUE TITLE
the highlight syntax is dazzle 

### ISSUE THREAD

**Issue by Johnskie-coded** [billthefarmer/editor#115]

**Comment by billthefarmer** [comment]
So I looked it up in the [urban dictionary - dazzle](https://www.urbandictionary.com/define.php?term=Dazzle)!

**Comment by Johnskie-coded** [comment]
dazze- intense light

the syntax highlighter is dazzle, please change it's color that good to see in the eye

**Comment by billthefarmer** [comment]
The highlight colours have to work against a dark and a light background, so pale pastel shades won't work.
