### ISSUE TITLE
Double space full stop in Gboard

### ISSUE THREAD

**Issue by spicemustflow** [billthefarmer/editor#116]
There is a feature in Gboard, which is incorrectly working in app. It's "Double space full stop" (Gboard settings -> Text correction). It doesn't auto capitalize the first word next to the dot, like it should.

**Comment by billthefarmer** [comment]
It's because I didn't choose the `textCapSentences` input type as the editor is intended for editing arbitrary text files, not necessarily documents. It works in my Notes and Diary apps as they are intended for editing documents.
