### ISSUE TITLE
EACCES permission denied when writing on SD-Card

### ISSUE THREAD

**Issue by gaellafond** [billthefarmer/editor#118]
Thanks, I like this text editor.

When I try to save to my SD-Card, it says:
EACCES (Permission denied)
NOTE: It does NOT say "Access", this is not a typo.
![Screenshot_20201015-213549](https://user-images.githubusercontent.com/936244/96136613-6e65a700-0f2e-11eb-82f3-e54ac08e5cd7.png)

Error occurs when saving new file to SD, save-as to SD and open file from SD and try to save it after modifying it. The SD card is fine, I can move file back and forth using the file explorer.

Android 10

**Comment by billthefarmer** [comment]
I have had issues raised on other apps about SD cards. Most devices seem to allow reading, but not writing by apps. I have decided that storing files on SD cards is not supported. The error message is the standard android message from [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L1880).

**Comment by gaellafond** [comment]
Thanks billthefarmer

I started to read about the subject. It's frustrating, it feels like Android is preventing apps to write to SD to "protect" you. I don't need that childish protection, I wish I could trun it off!

The protection can be bypassed by hacking some system files as root. I haven't rooted my phone yet, I don't really want to go that route.

Apps can implement the "request permission on demand" to write to SD cards, under APIv29. I suspect that would solve my problem. But I suspect that's not very high on the developers' priority list...

**Comment by billthefarmer** [comment]
The problem with SD cards, apart from not being able to write, is that if you reference a file from an app, like the **Open recent** in Editor, the `/3532-3833/` part of the path may change if you take the card out, use it elsewhere, and put it back in. The path may not be persistent.
