### ISSUE TITLE
Add text auto rename

### ISSUE THREAD

**Issue by sheryuan** [billthefarmer/editor#121]
Can I automatically set a new file name when creating new text? When I create new text, I use a unique file name by default Untitled.txt , which will cover my old documents. When I am busy, this may cause irreversible consequences.

by Baidu Translate.

**Comment by billthefarmer** [comment]
Don't save `Untitled.txt` files, use the **Save as** option.

**Comment by sheryuan** [comment]
It's ok, but I hope it can be added. After all, the save button is obviously simple and more direct, and if you are careless for a moment add subconsciously click save after writing, it will easily cause data loss.At least add one button to choose to overlay existing files.

**Comment by NitroNils** [comment]
Maybe default save button should go to 'save as'? Who ever saves their edits as "editor/untitled.txt" anyway?

**Comment by sheryuan** [comment]
emmmm.Or add a confirmation override?
