### ISSUE TITLE
[feature request]  .odt format

### ISSUE THREAD

**Issue by gbdomubpkm** [billthefarmer/editor#122]
Hello and thank you for your practical app that I just tried.
It would be great and very handy if you could add the .odt format: there's nothing simple and non-intrusive that takes into account this basic widely used format in Androïd non-paying apps.
Thanks in advance.

**Comment by billthefarmer** [comment]
It's a text editor, not a document editor. If you want a document editor, try my [Notes](https://github.com/billthefarmer/notes) app, but that doesn't support .odt either.

**Comment by gbdomubpkm** [comment]
ok thank you. I close.
Maybe you could add the idea (or not) for your Notes app.
