### ISSUE TITLE
[feature] fast scroll bar

### ISSUE THREAD

**Issue by disdaogitacc** [billthefarmer/editor#123]
something like

![](https://i.stack.imgur.com/I4vC5.png)

or 

![](https://androidopentutorials.com/wp/wp-content/uploads/2014/04/android-custom-scrollbar.png?1a8226)

thank you

**Comment by billthefarmer** [comment]
Well I looked at this and it would appear you can make the scrollbar as fancy as you like, but it doesn't appear make it do anything other than look nice.

![Screenshot_20210303-120121 1](https://user-images.githubusercontent.com/3448386/109803332-d5070b00-7c18-11eb-8e87-4c20e1d74c1e.png)

**Comment by disdaogitacc** [comment]
> 
> 
>it doesn't appear make it do anything other than look nice.

can you hold the scrollbar and scroll? if so well it sorta helps to scroll faster

**Comment by billthefarmer** [comment]
Well, out of interest, I had a look at the [sources](https://github.com/aosp-mirror/platform_frameworks_base/blob/master/core/java/android/widget/ScrollView.java). All the scroll view does is turn the scrollbars on and off. Further up the view hierarchy,  view group is interested in pointer events involving the scrollbar, so it may be if you have an external mouse or touchpad, it may do something.

**Comment by disdaogitacc** [comment]
i'm not an android dev so can't really help where in the source codes to take a look at, but there's a fast scrollbar implemented in [OctoDroid](https://github.com/slapperwan/gh4a)(a github client) or in the app drawer of [KISS launcher](https://github.com/Neamar/KISS)

cheers
