### ISSUE TITLE
Editor don't save on sd card (external memory)

### ISSUE THREAD

**Issue by marker10** [billthefarmer/editor#126]
Editor file read only on sd card, external memory access denied.  Editor not save. Android 10.

**Comment by billthefarmer** [comment]
Editing files on an SD card is not supported. This is in the [README](https://github.com/billthefarmer/editor#sd-cards).

**Comment by marker10** [comment]
will it be added in the future?

**Comment by billthefarmer** [comment]
Unlikely, because android doesn't allow apps to write to the SD card, and also if you take the card out, use it elsewhere and put it back the path may change. See #118.

**Comment by CrackedMatter** [comment]
Storage access framework?

**Comment by billthefarmer** [comment]
There is a problem with that in that it is necessary to provide a mime type. Android doesn't recognise a lot of commonly used file extensions, so can't check the mime type, which is why I created the built in file picker. On creating a file, the extension is forced by the given mime type, so if the user saved a file as `test.lua`, it might be saved as `test.lua.txt`, for example. Also I am not convinced that URIs or paths for files on a removable SD card are persistent. Not tested.

**Comment by marker10** [comment]
> Unlikely, because android doesn't allow apps to write to the SD card, and also if you take the card out, use it elsewhere and put it back the path may change. See #118.

To save or edit on the sd card, android asks you to mount the sd and you get permission to write. Other text editors I use on Android edit and save files on the SD.

**Comment by billthefarmer** [comment]
The problem with using the internal file manager as a file picker is that it returns a content Uri which allows an app to read and possibly write to the file, but may not be resolvable to a real file on the device. This means that several things that have been built into the app won't work:
 * Many file commonly used extensions won't be recognised as text files, so won't be opened. This is why I added the built in file picker
 *  The **Open recent** feature won't work
 *  The **Find all** feature won't work
 *  Remembering the edit position of recent files won't work
 *  Detecting and prompting for changed files won't work

**Comment by billthefarmer** [comment]
OK, I have added a storage button to the file chooser which uses the android file manager to open files. Using this, files may be saved on an SD card. The above caveats may apply. The save as menu item also uses the android file manager. This enables files opened on an SD card with the file chooser to be saved on an SD card.

**Comment by marker10** [comment]
> OK, I have added a storage button to the file chooser which uses the android file manager to open files. Using this, files may be saved on an SD card. The above caveats may apply. The save as menu item also uses the android file manager. This enables files opened on an SD card with the file chooser to be saved on an SD card.

Thanks 🙂

**Comment by gbdomubpkm** [comment]
For Info : Yesterday, i downloaded an update of  SimpleTextEditor F-Droid app (Maxim Starikov) 
https://f-droid.org/en/packages/com.maxistar.textpad/
I don't know how M. S. did,  but I can now save on SD   card (tested on android 9 base). It didn't work before this 1.16.1 update.

**Comment by billthefarmer** [comment]
I had a look, the app uses the same API as I have used. I haven't tested it, but I think it may have the same problem with widely used but unrecognised file extensions.
