### ISSUE TITLE
FR: autosave option

### ISSUE THREAD

**Issue by sciamano** [billthefarmer/editor#13]
I switched to your editor from https://github.com/no-go/TextThing and the only thing I am missing is the autosave feature. Could you introduce a setting for it either globally or maybe even better per files?

**Comment by billthefarmer** [comment]
OK, that's a good idea that I hadn't thought of. I like the idea of a retro theme as well, except it should be green on black, that chap isn't old enough!

**Comment by billthefarmer** [comment]
OK, that's in the next version, with a retro theme and the option to turn off text suggestions, #14.

**Comment by sciamano** [comment]
just checked the new version from f-droid: is does autosave on pressing "home"-button, but when i press "back" on edited text it still ask save or not...

**Comment by billthefarmer** [comment]
That's intentional, asking if you really want to discard a modified file if you do something that would delete the text, but saving it if something happens to make the app go into the background, like getting a phone call.
