### ISSUE TITLE
Same as #134 ("Editing files has become buggy, not saving changes and garbage added to the end of files on save")

### ISSUE THREAD

**Issue by jaimet** [billthefarmer/editor#138]
Essentially the same set of symptoms as #134, but a different environment:

Phone: OnePlus 5T
OS: Stock (OxygenOS version 10.0.1 = Android 10)
File location: /storage/emulated/0/Download/notes.txt

Unfortunately the file contains sensitive info so I can't upload it, but it has essentially the same form as a 10 kilobyte shopping list. I'll see if I can find a way to trigger this bug consistently and I'll see whether the logcat contains anything interesting. Sorry I don't have anything more concrete.

**Comment by jaimet** [comment]
Ok, I've just hit this bug again.

I was editing an 800-line text file, and I deleted 2 consecutive lines near the end of the file. I then saved the file and re-opened it. Only the first half of the first line had been deleted.

However, I cannot "trip" it consistently (and that's after a couple of hours of trying), so I presume that it's some kind of race condition.

Quick question: do
https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L2058
and
https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L2079
definitely not need any form of "flush" or "close"? :thinking:

**Comment by billthefarmer** [comment]
No, because the try-with-resources statement opening the stream ensures that it is closed. See https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html.
```java
        try (OutputStreamWriter writer = new OutputStreamWriter(os))
        {
            writer.append(text);
        }
```
One or the other of these source lines you have linked to are all the code in the app related to saving files, the rest is delegated to the android Java library. This app has been around for a long time and it is only very recently that this issue has come up. It is the most popular of my apps, judging by the number of stars it gets on here, which suggests to me it is widely used.

**Comment by billthefarmer** [comment]
To check that this Java code using the try-with-resources statement does indeed close the stream, I decompiled the apk using [apktool](), which produced this Smali code. It's not too difficult to follow. There are two `close()` statements, one invoked if the `append()` is successful, and one if the `append()` causes an exception.
```smali
.method private write(Ljava/lang/CharSequence;Ljava/io/OutputStream;)V
    .locals 2
    .annotation system Ldalvik/annotation/MethodParameters;
        accessFlags = {
            0x0,
            0x0
        }
        names = {
            "text",
            "os"
        }
    .end annotation

    .line 2078
    :try_start_0
    new-instance v0, Ljava/io/OutputStreamWriter;

    invoke-direct {v0, p2}, Ljava/io/OutputStreamWriter;-><init>(Ljava/io/OutputStream;)V
    :try_end_0
    .catch Ljava/lang/Exception; {:try_start_0 .. :try_end_0} :catch_0

    .line 2080
    :try_start_1
    invoke-virtual {v0, p1}, Ljava/io/OutputStreamWriter;->append(Ljava/lang/CharSequence;)Ljava/io/Writer;
    :try_end_1
    .catchall {:try_start_1 .. :try_end_1} :catchall_0

    .line 2081
    :try_start_2
    invoke-virtual {v0}, Ljava/io/OutputStreamWriter;->close()V      <<<=== Success, close stream
    :try_end_2
    .catch Ljava/lang/Exception; {:try_start_2 .. :try_end_2} :catch_0

    const/4 p1, 0x0

    .line 2090
    iput-boolean p1, p0, Lorg/billthefarmer/editor/Editor;->changed:Z

    .line 2091
    invoke-virtual {p0}, Lorg/billthefarmer/editor/Editor;->invalidateOptionsMenu()V

    return-void

    :catchall_0
    move-exception p1

    .line 2078
    :try_start_3
    throw p1
    :try_end_3
    .catchall {:try_start_3 .. :try_end_3} :catchall_1

    :catchall_1
    move-exception p1

    .line 2081
    :try_start_4
    invoke-virtual {v0}, Ljava/io/OutputStreamWriter;->close()V      <<<=== Fail, close stream
    :try_end_4
    .catchall {:try_start_4 .. :try_end_4} :catchall_2

    :catchall_2
    :try_start_5
    throw p1
    :try_end_5
    .catch Ljava/lang/Exception; {:try_start_5 .. :try_end_5} :catch_0

    :catch_0
    move-exception p1

    const p2, 0x7f070001

    .line 2085
    invoke-virtual {p1}, Ljava/lang/Exception;->getMessage()Ljava/lang/String;

    move-result-object v0

    const v1, 0x7f070016

    invoke-direct {p0, p2, v0, v1}, Lorg/billthefarmer/editor/Editor;->alertDialog(ILjava/lang/String;I)V

    .line 2086
    invoke-virtual {p1}, Ljava/lang/Exception;->printStackTrace()V

    return-void
.end method
```

**Comment by billthefarmer** [comment]
The most recent change to this app was to add the word and character count. The function is added to a queue after a short delay to run when the app isn't doing anything else. It's possible if a user makes a change and then immediately taps save that this would coincide with the save function. This shouldn't happen because the app can only do one thing at once, but I have made a small change to remove this and the highlighting from the queue on save.

**Comment by jaimet** [comment]
Bill, if it's easily done, could you please add an apk file to the assets for [this release](https://github.com/billthefarmer/editor/releases/tag/v1.59)? (Unfortunately I don't have a compile environment set up at the moment). Many thanks, Jaime

**Comment by billthefarmer** [comment]
I wait until F-Droid have build the app and published it to populate the releases. That way there is only one version of my apps and they will automatically update via F-Droid.

**Comment by smallcreek** [comment]
I can reproduce this reliably using org.billthefarmer.editor v1.59 downloaded from F-Droid running on an HMD (Nokia) device with Android 10.  For me, the symptom is that the file is not truncated when saving after shortening.  I do not remember exactly when I first noticed the problem.

Steps to reproduce:
1. Create a new empty file test.txt (I used Material Files to do this).  Open test.txt in Editor.
2. Type "qwerty"<newline> and save the file.  Line/character count shows 1/7.
3. Reopen the file, position the cursor between "w" and "e" and type backspace twice.  Screen now shows "erty". Save the file.  Line/character count is 1/5.
4. Reopen the file.  Screen now shows one line "erty" and a second line "y".  Line/character count is 2/7.

[test.txt](https://github.com/billthefarmer/editor/files/6794919/test.txt)

**Comment by billthefarmer** [comment]
Good, now I've got something to investigate.

**Comment by billthefarmer** [comment]
I can't reproduce this on a Moto G running android 7.12, but I can on a Samsung Tab A 8 running android 11, but only when using the storage API. I have tried adding a buffered writer and using `flush()`, which makes no difference. I have also tried a more tortuous route to a file writer via a parcel file descriptor, but that also makes no difference.

It would appear that on some devices writing a file via the storage API can be flaky. The relevant code is below. I am open to suggestions.
```java

    // saveFile
    private void saveFile(Uri uri)
    {
        CharSequence text = textView.getText();
        // try (OutputStream outputStream =
        //      getContentResolver().openOutputStream(uri))
        // {
        //     write(text, outputStream);
        // }

        try (ParcelFileDescriptor fd =
             getContentResolver().openFileDescriptor(uri, "w"))
        {
            write(text, fd);
        }

        catch (Exception e)
        {
            alertDialog(R.string.appName, e.getMessage(), R.string.ok);
            e.printStackTrace();
            return;
        }
    }

    // write
    private void write(CharSequence text, ParcelFileDescriptor fd)
    {
        try (BufferedWriter writer =
             new BufferedWriter(new FileWriter(fd.getFileDescriptor())))
        {
            writer.append(text);
            writer.flush();
        }

        catch (Exception e)
        {
            alertDialog(R.string.appName, e.getMessage(), R.string.ok);
            e.printStackTrace();
            return;
        }

        changed = false;
        invalidateOptionsMenu();
    }

    // write
    private void write(CharSequence text, OutputStream os)
    {
        try (BufferedWriter writer =
             new BufferedWriter(new OutputStreamWriter(os)))
        {
            writer.append(text);
            writer.flush();
        }

        catch (Exception e)
        {
            alertDialog(R.string.appName, e.getMessage(), R.string.ok);
            e.printStackTrace();
            return;
        }

        changed = false;
        invalidateOptionsMenu();
    }
```

**Comment by jaimet** [comment]
Weird - I cannot reproduce the bug using the steps listed in [@smallcreek's comment](https://github.com/billthefarmer/editor/issues/138#issuecomment-877598565). The more time I spend on this bug, the less I understand it. :upside_down_face:

**Comment by billthefarmer** [comment]
It works every time on my Samsung. I either get
```
erty
y
```
or
```
ertyty
```
But only when saving via Storage. And not on a Moto G. The annoying thing is that one potential fix would be to delete the file before writing, but there's no API to do that via Storage, only the two I tried above.

**Comment by jaimet** [comment]
> I can on a Samsung Tab A 8 running android 11, but only when using the storage API.

> But only when saving via Storage.

I'm confused. What's the alternative?

**Comment by billthefarmer** [comment]
If you open a file using Storage or from another app, it will be saved via Storage. This is so that files opened on an SD card will save successfully. If you open it using the built in file browser, it will be saved via the Java File API. If you save it via Save as it will be saved via the Java File API, unless you use Storage. This app just used the Java File API until Google started adding idiotic security restrictions.

**Comment by billthefarmer** [comment]
I wrote a bare bones app that tests the Storage API as above, which fails on an android 10 emulator.

![Screenshot_1626120515](https://user-images.githubusercontent.com/3448386/125349712-cb737980-e355-11eb-923c-cebf9ac359a0.png)

And works correctly on an android 7.1.1 emulator.

![Screenshot_1626120914](https://user-images.githubusercontent.com/3448386/125350241-68cead80-e356-11eb-8d59-516ddb3f5aec.png)

**Comment by billthefarmer** [comment]
I have found this issue on the [Google issue tracker](https://issuetracker.google.com/issues/180526528), with a suggested 'fix', which I have tested. That will be in the next version.

**Comment by jaimet** [comment]
> I have found this issue on the [Google issue tracker](https://issuetracker.google.com/issues/180526528)

Wow. I am completely speechless. That is nothing short of insane (in my opinion). :flushed:
Well found, Bill. :clap: :thumbsup:

**Comment by jaimet** [comment]
Closing. And thank you for the best (IMHO) simple text editor on android. :pray:
