### ISSUE TITLE
Toggle spell check

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#14]
An option to toggle the spell checker on or off would be useful, for example when looking at code.

**Comment by billthefarmer** [comment]
I will look at that.

**Comment by billthefarmer** [comment]
Ok, that's in the next version. It doesn't behave exactly as one would expect, if you type a buffer full of gibberish, the gibberish is underlined in red and the keyboard shows suggestions. If you turn the suggestions off, the red underlining disappears and the suggestions disappear. If you turn it back on again, only new gibberish is highlighted and the suggestions reappear.
