### ISSUE TITLE
` Ctrl+S` support on tablet device

### ISSUE THREAD

**Issue by xzjladmin21** [billthefarmer/editor#142]
Android tablet device.

**Comment by billthefarmer** [comment]
I have two questions:
1. What makes you think this app doesn't support tablets?
2. How do you type `Ctrl-S` on a standard android keyboard?

**Comment by xzjladmin21** [comment]
I use HUAWEI MatePad Pro , using bluetooth keyboard, this app works very fluently on  it, but don't support CTRL+S like Office does.

CTRL+S, just to save txt like the way in PC, such as Windows OS .( Save  txt directly by using keyboard shortcut)

**Comment by billthefarmer** [comment]
The next version will have some keyboard shortcuts in it. It took me a long time to find an external keyboard emulator that actually works. I ended up with [scrcpy](https://github.com/Genymobile/scrcpy), with the added bonus of display as well.
