### ISSUE TITLE
loding default file while share

### ISSUE THREAD

**Issue by ulrichloose** [billthefarmer/editor#143]
A small mistake:

The default for saving is editor.txt. If you transfer a text to the editor via share and a file called editor.txt is already saved, a combination of the editor.txt file plus the transferred share text is combined and displayed.

An already existing file with the standard name must not be loaded when passing a text via share ...

**Comment by billthefarmer** [comment]
OK, I missed that one when adding the new button.

**Comment by ulrichloose** [comment]
Thank you very much - everything is now working as it should ...

**Comment by SebiderSushi** [comment]
Hello i would like to add that i was in fact using this behavior as a feature. I found it useful to share liks or other notes to collect them all in one file over time.

Is it possible to support this use-case again? If you think that would be too bloated it would also be ok for me. I can use the older version or compile from source if need be. Just chiming in to say that this is a possible use-case.

In case you decide to support the use-case i described i'd like to add that v. 1.60 did add a new activity (and thus another entry on the "recently used" screen) everytime a share was delivered to Editor. For the use-case, an existing activity would preferrably be reused. The shared text would be added without creating an additional activity.

**Comment by billthefarmer** [comment]
The behaviour you describe is standard for android apps, determined by the `android:launchMode` entry in the [activity](https://developer.android.com/guide/topics/manifest/activity-element) section of the app manifest. You have to scroll a long way down to find it.

> android:launchMode
    An instruction on how the activity should be launched. There are four modes that work in conjunction with activity flags (FLAG_ACTIVITY_* constants) in Intent objects to determine what should happen when the activity is called upon to handle an intent. They are:

>    "standard"
    "singleTop"
    "singleTask"
    "singleInstance"

>    The default mode is "standard".

>    As shown in the table below, the modes fall into two main groups, with "standard" and "singleTop" activities on one side, and "singleTask" and "singleInstance" activities on the other. An activity with the "standard" or "singleTop" launch mode can be instantiated multiple times. The instances can belong to any task and can be located anywhere in the activity stack. Typically, they're launched into the task that called startActivity() (unless the Intent object contains a FLAG_ACTIVITY_NEW_TASK instruction, in which case a different task is chosen — see the taskAffinity attribute). 

My apps default to "standard" as it's not specified in the manifest.

**Comment by SebiderSushi** [comment]
Thank you for your reply.
