### ISSUE TITLE
Share in mainmenu...

### ISSUE THREAD

**Issue by ulrichloose** [billthefarmer/editor#144]
Occasionally I want to print a text from the editor or convert it to a PDF. For this I use a small app called text2print from 402d at github. The text would have to be transferred to this app via share, which is also a bit cumbersome via "mark all" popup menu share. Wouldn't it make more sense to have share in the main menu so that the entire text can be passed on without detours?

If Bill is looking for a challenge, it would of course be optimal to implement a print / PDF option right away. I'm just a layman, but it seems to me that almost everything is already there: markdown view = WebView? All that's missing is a standard PrintDocumentAdapter for Webview including a button ... (:-)

**Comment by billthefarmer** [comment]
Well this is interesting. There are several points:
* Editor doesn't contain a WebView, the `View markdown` menu option uses the commonmark markdown library to produce HTML, writes the HTML to a file in the app's private cache, and offers the file to any app that wants to open it. Which doesn't include TextToPrint.
* TextToPrint will open text files, which makes me wonder why not HTML as it uses a WebView.
* Why open a text file with Editor only to share the text with TextToPrint which could do it itself?
* I checked out some of the apps on my Samsung tablet to see which ones offered printing
  *  Google Chrome &ndash; no
  *  Firefox &ndash; no
  * Google news app &ndash; no
  * Samsung Email &ndash; yes
  * Samsung Gallery &ndash; yes

It seems to me you want me to add functionality to my app to compensate for the inadequacies of TextToPrint.
Perhaps you should ask them why they don't support HTML files.

**Comment by ulrichloose** [comment]
Please don't misunderstand - my main concern was a share button in the main menu and not just a share for selected text. That would make it easier to print out or create a PDF from the editor. Of course, it is also possible to open the corresponding text file directly in this tool.

The installation of a print function was only due to my layperson's assumption that there was a Webview component anyway and one "only" had to add a little something createWebPrintJob () ...

That was a misunderstanding and not an attempt to persuade ...

**Comment by billthefarmer** [comment]
Well, IMHO, it's redundant.
