### ISSUE TITLE
Option to disable scaling gestures

### ISSUE THREAD

**Issue by statesecret** [billthefarmer/editor#145]
Option to disable scaling gestures

**Comment by billthefarmer** [comment]
Why? If you don't use two fingers or double tap and swipe, nothing happens.

**Comment by statesecret** [comment]
It can occur even with one finger, for usually multiple times when selecting text to cut & paste or simply scrolling. You'll notice it quite easily when trying holding a finger to select more than one line, imitating the "shift & hold" command of text selection.

**Comment by billthefarmer** [comment]
I can't reproduce that, you have to double tap and swipe in one go to get scaling.
