### ISSUE TITLE
FR: Allow long touch in blank space to paste text when no file is open

### ISSUE THREAD

**Issue by aviladev** [billthefarmer/editor#146]
Hi, I mainly use Editor as a temporary place where I can write something that will be discarded soon, so I'm not manipulating any files.

That said, it would be great if I could open the app with my right hand and long touch anywhere in the blank space to paste some text.

Currently I have to specifically long touch at the top of the app where there is a line.

Anyway, thank you for the great app!

**Comment by aviladev** [comment]
Wow, looks like there are two apps called "Editor" in my phone and I misconcepted them 😅. The other one's ID is oppen.editor which is alson on F-Droid.

I'm sorry, for the confusion, I'm closing this.

**Comment by billthefarmer** [comment]
I couldn't find that app on [F-Droid](https://search.f-droid.org/?q=Editor&lang=en).

**Comment by aviladev** [comment]
I didn't even notice that, but it's actually in the [IzzyOnDroid repository](https://apt.izzysoft.de/fdroid/index/apk/oppen.editor), which I added to my F-Droid app.

Anyway, I found your Notes app, which works pretty much the way I needed. Also found another cool [Notes app in the Izzy repo](https://f-droid.org/packages/org.astiansuite.notes).
