### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by YYYSSSHHH** [billthefarmer/editor#148]
**Environment Info：**
APK Version: 1.61 (161) 
Android simulator version: 6.0.1

**Repro Steps：**

Revoke storage permission of app in the background.
1.Click the "Navigation" button in the top right-hand corner of app.
2.Click the "Save as" button.
3.Long click  the "Edit_text".
4.Click the "SAVE" button, then the app will crash.
![55](https://user-images.githubusercontent.com/55122523/128625230-f62fc160-2860-4255-a7bd-e88a93dd1473.png)

**Do you judge this as a defect?**

**Comment by billthefarmer** [comment]
I can't reproduce that. On the phone I use for testing the keyboard obscures the save button, dismissimg it removes the highlight and the paste menu. On an emulator the system permissions dialog pops up.

![Screenshot_20210808-095430 1](https://user-images.githubusercontent.com/3448386/128626656-8e205839-53f7-42bc-95b0-19ad5205786b.png)

![Screenshot_1628412525](https://user-images.githubusercontent.com/3448386/128626684-ac2ad37f-98bb-4a7a-81ad-f8f032e60492.png)

**Comment by YYYSSSHHH** [comment]
Please grant storage permissions and try again.

https://user-images.githubusercontent.com/55122523/128627040-eac29d5b-752b-4297-b863-069901e1b318.mp4

**Comment by billthefarmer** [comment]
Unreproducable
