### ISSUE TITLE
Feature: using this encoding to reopen.

### ISSUE THREAD

**Issue by xzjl20210814** [billthefarmer/editor#150]
Feature: using this encoding to reopen.

A list to choose encoding like UTF8, GBK, GB18030, and others.(encoding change)

Because some txt opened, but garbled.

Change encoding of txt to solve garbled data.(Or Auto-Detect many chracter codes)

**Comment by xzjl20210814** [comment]
OR Auto-Detect multiple character codes.

**Comment by billthefarmer** [comment]
See https://github.com/billthefarmer/editor/issues/128#issuecomment-841791159

**Comment by xzjl20210814** [comment]
Some apps use .ini file to save settings.
And .ini opened but garbled.
I have to open it in Office.

estrongs.com/?lang=en
Note Editor tool of ES Folder app Supports this feature.

Expecting to be supported in Editor too.

**Comment by billthefarmer** [comment]
[ES File Explorer](https://en.wikipedia.org/wiki/ES_File_Explorer) is a file manager/explorer designed by ES Global, a subsidiary of DO Global, for Android devices. It includes features like cloud storage integration, file transfer from Android to Windows via FTP or LAN,[1] and a root browser. It was removed from the Google Play Store for committing click fraud. ([Wikipedia](https://en.wikipedia.org/wiki/ES_File_Explorer))
