### ISSUE TITLE
paste shortcut (ctrl+V) broken

### ISSUE THREAD

**Issue by asmanel** [billthefarmer/editor#151]
I often have to copy and paste text in this program.

To do it, I use shortcut, ctrl+X (cut), ctrl+C (copy) and, until recently , ctrl+V (paste).

Recently, new shortcuts were added. Before , the lack of several of them were part of the cons of this text editor

The problem is with the shortcut ctrl+V. Before, it was used to paste. Now, it switch to the view mode instead.

To paste, now, I have to use a contextual menu that isn't practical at all.

**Comment by billthefarmer** [comment]
OK, I missed that. I have changed it to Ctrl+Shift+E., as there isn't a viable acronym for View.
