### ISSUE TITLE
ignore case text search

### ISSUE THREAD

**Issue by RFDAJE** [billthefarmer/editor#154]
First a BIG thanks to the dev who brought us such a amazing and useful App. 

I am using Version 1.62, it seems that editor does only case sensitive search, is there a setting to make it ignore case?

**Comment by billthefarmer** [comment]
The text search uses [Regular Expressions](https://en.wikipedia.org/wiki/Regular_expression) which means that you can search for just about anything. For example `[Ss]elect` will find `Select` or `select`. It's also interactive, so it will probably find what you want before you have finished typing in what you are looking for.

**Comment by RFDAJE** [comment]
Good to know text search supports regex. If I want to match both "SELECT" and "select", it is a little bit tedious to type [Ss][Ee][Ll][Ee][Cc][Tt].

**Comment by RFDAJE** [comment]
use `(?i)select` for ignorecase search, it will match both.
