### ISSUE TITLE
Are icons a little too big?

### ISSUE THREAD

**Issue by GiovanniSalmeri** [billthefarmer/editor#157]
Thank you very much for your excellent Editor, it suits perfectly my needs! Just a tiny fussy remark regarding the icons: aren't they a little too big? I do not know if there are guidelines in Material style, but all other apps I use have somewhat smaller icons (pencil, floppy ecc.) and so Editor seems esthetically a bit out of place among them.

**Comment by billthefarmer** [comment]
All the UI icons in my apps are from resources provided by Google on the android developers site. They come in a selection of sizes, it's down to the implementation of the android UI on each device to pick the appropriate size. The actual app icons are provided in a range of sizes as well. See https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp

**Comment by GiovanniSalmeri** [comment]
Strange... Anyway I know too little about Android to be able to say anything sensible about that. I consider the issue closed, thank you very much for the answer!
