### ISSUE TITLE
Syntax highlighting does not work for shell script files

### ISSUE THREAD

**Issue by ioogithub** [billthefarmer/editor#158]
I have been using Editor for over a year, I always had Settings-> Highlight syntax checked however it has never worked. 

I am working with bash shell script files. They have a shebang as the first line and end in the extension *.sh.

How do you detect these files to highlight?

I have used multiple versions, currently using version 1.63 from fdroid.

**Comment by billthefarmer** [comment]
Well I just checked the code, and it's all present and correct, so I wrote a spoof shell script because I can never remember the syntax and that works too.

![Screenshot_20210920-113921 1](https://user-images.githubusercontent.com/3448386/133989890-c7b9f42f-aa3f-4a11-9a8a-16ff6fc3b53c.png)

**Comment by shakna-israel** [comment]
![Screenshot_2022-04-03-17-42-38-986](https://user-images.githubusercontent.com/2098729/161417136-f52ff47b-6425-4b7e-9dea-b6ea3794ea86.jpeg)

The syntax highlighting for shell in v1.71 does not seem to tokenise nearly as nicely as your demo script.

**Comment by billthefarmer** [comment]
The shell script highlighting highlights comments, keywords, constants in ALL_CAPS and numbers. It's done that in your script, which has few keywords. The [README](https://github.com/billthefarmer/editor#readme) and [Syntax](https://github.com/billthefarmer/editor/blob/master/Syntax.md) make it quite clear that no attempt at parsing is made.

**Comment by billthefarmer** [comment]
OK, the next version will highlight shell referenced variables `$some_thing, $(exp), ${whatever}` and operators.
