### ISSUE TITLE
Copy, Paste gesture confused with pinch gesture

### ISSUE THREAD

**Issue by OldGuit** [billthefarmer/editor#163]
Android 11 / OxygenOS 11.1.1.1 Editor 1.65

When first opened, Editor is ignoring select gestures (double tap / long press).
If zoom-in-out gesture used (pinch or spread) select gestures start working again and pop-up Paste Cut, etc menu reactivated.

**Comment by billthefarmer** [comment]
The app defaults to opening files in view mode, unless that is changed by the user. In view mode double tap gestures are ignored by the text view that implements the editor functionality and long press gestures are handled by the app and switch to edit mode. Once in edit mode, double tap gestures and long press gestures are handled by the text view and result in selections.

Using the scale gestures it's quite likely to also inadvertently cause a long press gesture to be detected resulting in a switch to edit mode and the above behaviour.

**Comment by OldGuit** [comment]
> The app defaults to opening files in view 
In my experience too.

> long press gestures are handled by the app and switch to edit mode
In my situation also.

> Once in edit mode, double tap gestures and long press gestures are handled by the text view and result in selections.
Not for me.
Unless I change text size, I cannot use usual gestures to make selections and the Copy, Select, Paste, etc pop-up menu fails to appear. If I change text size, by any means, I cannot make gesture-based selections and the Copy, Paste, etc pop-up menu fails to appear,

**Comment by billthefarmer** [comment]
OK, I have added yet another kludge to the app to temporarily change the text size when switching to edit mode. I can't test it because it works fine on the devices I have, so I will put a debug version here. If you can test it and it works that will be in the next version.

[Editor-debug.zip](https://github.com/billthefarmer/editor/files/7448834/Editor-debug.zip)

**Comment by OldGuit** [comment]
Tested. Still suffers the same issue.
Incidentally, pinch or spread gestures result in more sizes than the three options on the menu. As well as Small Medium and Large, I can get Giant and Minute.

**Comment by billthefarmer** [comment]
OK, The huge and tiny sizes are limits to the scale gestures and I also used them for temporarily changing the text size. I have added code to recreate the activity. I have put a debug version here for you to try.

[Editor-debug.zip](https://github.com/billthefarmer/editor/files/7452175/Editor-debug.zip)
