### ISSUE TITLE
[REQUEST] Show File Name For Long Paths

### ISSUE THREAD

**Issue by pyramid3d** [billthefarmer/editor#164]
Currently the open recent dialog shows the full path with filename. When the path is too long, the file name cannot be seen.

E.g.
/storage/0000-1111/datafolder/subfolder/project/file1.txt
/storage/0000-1111/datafolder/subfolder/project/file2.txt

will show both as
/storage/0000-1111/datafolder/subfo...
/storage/0000-1111/datafolder/subfo...

It would be better to show the full filename and cut the preceding path to the remaining string length available, e.g.
/storage/00.../subfolder/project/file1.txt
/storage/00.../subfolder/project/file2.txt

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

![Screenshot_20211110-153147 1](https://user-images.githubusercontent.com/3448386/141143058-6da2640a-4350-489c-9cdc-9982b6291a29.png)

**Comment by pyramid3d** [comment]
Thanks for considering this and replying in such an exceptionally short time ;-)

**Comment by pyramid3d** [comment]
Hmm strange thing is that if I open a file with long path name, then close the editor, and try to open it via open recent, it will not open.

**Comment by billthefarmer** [comment]
OK, I have managed to fix it. I couldn't get the [API ](https://developer.android.com/reference/android/view/MenuItem#setTitleCondensed(java.lang.CharSequence)) to work as documented, so I have inverted the logic to keep the original path. That will be in the next version.

**Comment by pyramid3d** [comment]
Works great now! :+1: :-D
