### ISSUE TITLE
Share file function in the menu

### ISSUE THREAD

**Issue by THUzxj** [billthefarmer/editor#167]
Hello,

Thank you for this powerful application.

Would you like to add a share function to the menu? In some scenarios, people may need to send some text messages on the phone to the PC without logging in IM services either on the phone or the PC. And it enables us to share files with other applications. Although I can reach the files in the file manager and share them, it is hard to find the right directory.

If you accept to add this function, I am ready to offer some work on it.

**Comment by billthefarmer** [comment]
I have tested this, it may not do what you were thinking of. If you select all the text and then share it you get...

![Screenshot_20220117-092259 1](https://user-images.githubusercontent.com/3448386/149743021-aec0a89a-b84e-44e7-911a-1ca8fb11b153.png)

If you share the file you get...

![Screenshot_20220117-092335 1](https://user-images.githubusercontent.com/3448386/149743311-44c18abd-2246-45fe-9b2e-f2b29393878e.png)

**Comment by THUzxj** [comment]
Some vendors, like Xiaomi, Samsung, Huawei, customize the Intent.ACTION_SEND for more functions. The functions include sending files fastly to other computers, phones, and TVs, similar to airdrop. Maybe a share button can help those who use phones provided by those vendors.
This is the UI of ACTION_SEND in MIUI, including MiShare function:
<img src=https://user-images.githubusercontent.com/44231913/149817279-9d51b0f8-8392-4a4b-a1bd-112454295b5e.jpg width=50%/>

**Comment by billthefarmer** [comment]
I was using `ACTION_VIEW`, as I was sharing the file, as per your request. If you use `ACTION_SEND`, the result is that same as selecting the text and sharing it, irrespective of whether you send the Uri of the file or the actual text. I tried using `ACTION_SEND` for the **View markdown** function, which stopped web browsers and the HTML viewer showing up. So, this is somewhat redundant as you can do what you want using android built in functionality.
