### ISSUE TITLE
[feature request] Formatting

### ISSUE THREAD

**Issue by gbdomubpkm** [billthefarmer/editor#168]
Hello.
I like very much your app.
Could you please add these three basic (but usefull) formatting options: bold, italic, underlined.
To be used on selected parts/words.
Regards

**Comment by billthefarmer** [comment]
If I do that it wouldn't be a text editor. Try my [Notes](https://github.com/billthefarmer/notes) app for formatted text.

**Comment by gbdomubpkm** [comment]
Your Notes app does not suit me personally. It doesn't seem to have the automated options I'm looking for. It seems to me that you have to program or import from I don't know where the options you are looking for and I know nothing about that. For me (after a short try) less intuitive than the very nice editor. But thanks a lot for suggesting it. I close the issue
