### ISSUE TITLE
Feature Request: make files scrolling position be the same for files which were already opened in the past

### ISSUE THREAD

**Issue by doronbehar** [billthefarmer/editor#17]
Allow me to explain if the title wasn't clear enough:
When opening a large file where you have to scroll multiple pages to view all of it, it could be great if one could scroll to a certain position in the file and than after closing the app and even killing it, opening the same file will bring him to the same scrolling position he was when he last read/wrote in the file.
A spectacular example of an app that does so with extra customizations etc, is [Document Reader](https://github.com/PrivacyApps/document-viewer) ([available on F-Droid](https://f-droid.org/app/org.sufficientlysecure.viewer)) which has an enormous amount of settings and I highly recommend it.

Pardon me if I overload this project with issues but I'd really like thus app to be even better than it is already.
What do you think?

**Comment by billthefarmer** [comment]
It's relatively easy to remember the last file that was opened and the position in it, not so easy for older files. I deliberately don't use this option in emacs because it makes it slow down once the list gets long. I will look at that.

**Comment by billthefarmer** [comment]
Well having said that I discovered that I do use this function, I must have turned it back on again after an upgrade. If you are going to save the position of a list of files, you've got the list to implement open recent files, so I have added that as well. That will be in the next version.

**Comment by doronbehar** [comment]
Sounds great, thanks!
