### ISSUE TITLE
Org files syntax highlighting

### ISSUE THREAD

**Issue by kauesena** [billthefarmer/editor#172]
Hi! I see you have markdown syntax highlighting. Could you add highlighting of `.org` files which are used for Emacs Org Mode?

**Comment by billthefarmer** [comment]
The syntax highlighting in is Editor is very simplistic, see [Syntax](https://github.com/billthefarmer/editor/blob/master/Syntax.md). It would be possible to do something similar to markdown, which just highlights header, links, and emphasis.

**Comment by kauesena** [comment]
I thought of something very simple as you said. Like the highlighting of
markdown already implemented. Making text bold or italic and making
headings stand  out with some color or by making them bold too.

My use case is that I share some org files between my phone and my
computer, where I edit them with emacs. On the phone, I only do very light
editing. Add a sentence or just some words to expand later.
