### ISSUE TITLE
Opening a file via an intent triggers "This file has changed" bug.

### ISSUE THREAD

**Issue by jaimet** [billthefarmer/editor#173]
Hi Bill.

If I start editor and then open a file *from within editor*, then all is good.

If, however, I use a file manager app to "open" a text file (such that it opens in editor), then this triggers the following bug in the ["Overwrite warning" code](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L2161):

1) Press any character on the keyboard to edit the file (this enables the "Save" toolbar item). Press the "Save" toolbar item to save the file (this reverts the "Save" toolbar item to a plus-sign).

2) Again, press any character on the keyboard to edit the file (again, this enables the "Save" toolbar item). Again, press the "Save" toolbar item to save the file. Instead of saving the file, this time you see the "This file has changed, do you want to overwrite it? Cancel/Overwrite?" warning dialog.

I'm not sure whether this is a peculiarity of my phone (OnePlus 5T)/operating system (OxygenOS v10.0.1) or whether this is something that other people can reproduce.

In case it helps, when I open the file in the file manager, adb logcat shows something along of the lines of:
```
04-26 14:26:49.600  1565  4042 D OemSceneCallBlock: isCallBlockedWithUidIntent { act=android.intent.action.VIEW dat=content://com.android.externalstorage.documents/document/primary:blank.txt typ=text/plain flg=0x20000003 cmp=org.billthefarmer.editor/.Editor }, ResolveInfo{622c3b1 org.billthefarmer.editor/.Editor m=0x608000}, false
04-26 14:26:49.603  1565  4042 I ActivityTaskManager: START u0 {act=android.intent.action.VIEW dat=content://com.android.externalstorage.documents/document/primary:blank.txt typ=text/plain flg=0x20000003 cmp=org.billthefarmer.editor/.Editor} from uid 10104 pid 27887
```

Might this have anything to do with the URI type being a content URI rather than a file URI? (Wild guess!)

Many thanks, Jaime (PS: this is with Editor v1.73)

**Comment by billthefarmer** [comment]
If a file is passed to Editor from an external app it will be as a content Uri. Editor attempts to resolve these Uris to a file, so the code you linked to can work correctly. This is often not possible. If you save the file, if you know where it **really** is, using **Save as**, then this should work correctly, and also the file will appear in the list of recent files, making it easy to edit it again. The content resolver system does not allow access to useful information like last modified date/times.

**Comment by jaimet** [comment]
Ok, _if I understand correctly_, in my situation (with a file loaded via an external app i.e. using a content URI), `file.lastModified()` will fail to return a meaningful value. I've checked the docs for [java.io.File's lastModified method](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#lastModified()) and they say that this method will return: 

> 0L if the file does not exist or if an I/O error occurs.

I don't understand how the alertDialog is being triggered if the boolean condition is evaluating to false. (If `file.lastModifed()` is 0 and `modified` is positive, then surely the conditional should evaluate to false and the alertDialog should not be triggered, no?)

There is something else that is confusing me. I've just tried editing my document with 10 "modify-save" cycles (i.e. press the "a" key then press the "save" button, rinse and repeat), and the only time that the alertDialog was triggered was immediately after the 2nd save click. I don't understand how the same boolean conditional could evaluate to false on the 1st, 3rd and all subsequent attempts, but true on the 2nd (and *only* the 2nd) attempt. Do you know what is happening here? (sorry - I have no android dev environment installed at the moment - otherwise I'd debug this myself.)

**Comment by lu-p-us** [comment]
Little late to the party, but I want to confirm jaimet's findings ... kind of.

If I open the editor app first and than open a text file from within the app, I can make changes and save them as often as I like without triggering the overwrite warning. In contrast, if I create a link to the text file on the "desktop", which opens the file with the editor app, I can make and save the first change without a warning, than get the warning after the second change, no warning after the third change, again warning after fourth change, and so on.

My device: Xiaomi Mi A1 with LineageOS 19.1 (Android 12).

No big deal if you are used to it and especially after reading Bill's explanation above, but still weird while seeing it happen for the first time.

**Comment by lu-p-us** [comment]
UPDATE: It depends on *how* you create the desktop link/shortcut. Before my previous post I did it with functionality provided by the Totel Command app. After the post and browsing through this repository, I (re-) discovered the [Version 1.86 Changelog](https://github.com/billthefarmer/editor/releases/tag/v1.86) --> "Add open file shortcut". Desktop shortcuts using this new feature do not suffer from the problem described above. Nice.

I suggest to close this issue.
