### ISSUE TITLE
Default homepage

### ISSUE THREAD

**Issue by 353fc443** [billthefarmer/editor#174]
Hi,
Thank you for the great work!
Can we have a default homepage instead of the `Editor.txt` file? 

Thanks :)

**Comment by billthefarmer** [comment]
I'm not sure exactly what you mean. The `Editor.txt` file is similar to the `*scratch*` buffer in emacs in that it doesn't exist unless you make it so. You can create a new file or open one and it's not there any more.

**Comment by 353fc443** [comment]
I'm saying that it would be better (my opinion)if I can close `Editor.txt` and land a home page to create new docs.
