### ISSUE TITLE
line numbers

### ISSUE THREAD

**Issue by hueldoeu** [billthefarmer/editor#175]
thank you for editor. i replaced jota+ with it. will you add line numbers to it one day?

**Comment by hueldoeu** [comment]
when i want to search for a word in the text file, i type the word into the searchbox. then let's say i want to add something BELOW the searchbox in the current text file or delete something. i click the cursor on the text file, it's not blinking in the text file anymore. after one press, mostly the first press of any button, so far the backspace button and any letter button, the cursor jumps back to the search box. then i have to press again to the text file content and then everything works.

**Comment by hueldoeu** [comment]
how can i search without looking for capital letters like if i search for "games" editor won't find the word "Games" because G is capital

**Comment by billthefarmer** [comment]
See #155. Check closed issues.

**Comment by hueldoeu** [comment]
sorry bill but i have have changed from editor to markor (net.gsantner.markor), also on f-droid. scrolling is superfast and since i had to learn the editorprogram markor from level 1 because it's new, i had discovered in the beginning, that it's autosaving every edit i do. somehow autosaving stopped working but it's still ok. sometimes autosave can be dangerous.
