### ISSUE TITLE
Improving readability of wrapped lines

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#176]
I often find wrapped lines hard to read. Is the line wrapped? Is there a new line? Where does this indented block end?

Vim has this feature:

>    :he breakindent
>    Every wrapped line will continue visually indented (same amount of
>    space as the beginning of that line), thus preserving horizontal blocks
>    of text.

Without line numbers and without reading the first line, it can be difficult to understand whether the first wrapped line is wrapped or a new line:

![nobreakindent](https://user-images.githubusercontent.com/985977/173222484-e253a5a2-dcec-4ab8-bc7b-e80d8c3f7f8d.png)

With *breakindent* it becomes somewhat easier (at least parsing the indented block becomes easier):

![breakindent](https://user-images.githubusercontent.com/985977/173222538-91d106f1-9140-48d2-9846-b0f9792b70de.png)

With *breakindent* and indentation indicators even more cases become clear (excluding unindented lines that wrap):

![lines](https://user-images.githubusercontent.com/985977/173222640-6010583b-d621-4594-a6c8-6db8ee04d448.png)

Unindented lines that wrap become clear with end-of-line characters:

![list](https://user-images.githubusercontent.com/985977/173222871-afa3a261-bf8c-4991-bbd0-33699af3d90a.png)

Inserting a character at the beginning of wrapped lines (e.g. ↳) is another possibility. This might pair well with *breakindent* and might be easier to implement than lines as indentation indicators. Vim uses `:set showbreak=↳` to enable this:

![wrap-indicator](https://user-images.githubusercontent.com/985977/173223216-10b6aafe-1e37-41a9-bd23-2fea433ef0fb.png)

**Comment by billthefarmer** [comment]
There are two points. First this app uses the android [TextView](https://developer.android.com/reference/android/widget/TextView) API to implement the basic text editing function. Implementing this would involve inserting blanks into the text in carefully calculated places and removing them again when the line is no longer in view or the file is saved. I'm not going there. Second the app offers word wrap as an option. Turn it off and you can scroll sideways to see what is what.
