### ISSUE TITLE
Saving behaviour with content provider on Android 9+ (Samsung)

### ISSUE THREAD

**Issue by ddeberhar** [billthefarmer/editor#179]
On different Samsung devices with Android 9, 11, 12 (background activity limited by power saving) I'm editing text files provided by EDS lite to (BillTheFarmer's) Editor: 
- if I press "Save" I'm offered a file selection dialogue instead of saving to where the text file came from,

The only way to save my edited text to EDS lite is to press the back button and select Save on the warning dialogue.

(My intention is to keep my texts private between EDS lite (no network permission) and Editor (no network permission - very rare among apps of this kind).)

If in EDS lite I set the option "Don't use EDS content provider to open files in other applications" - i.e. use temporary files - things get worse - so I'll stick with setting for using content provider:
- if I change to a different app and back (e.g. browser for copy-paste another portion of text or the URL), I may lose all changes made to my text after the first change to the other app, 
- unless - I have aute-save active, then I find my complete changed text saved to Documents/untitled.txt

Thus I'd have to press Back and Save every time, and re-open the file to continue editing. This is somewhat inconvenient, if I try to compose a text with citations or look-ups from several sources.
 (Ghost commander's Text editor shows a very long sequence of characters as filename, but no path with either EDS setting, Yet it has network permission. Editor does show the correct file name...)

I'd really appreciate it very much, if I'd have less to worry about safely storing my edited notes to the desired places. 

Many thanks,
Dirk

**Comment by billthefarmer** [comment]
OK, that was a regression caused by changing the notional file content uris get loaded into to the new file from the default file.
