### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by Ygarr** [billthefarmer/editor#180]
Please no. I have such txt  which used
![Screenshot_20221026-045752_1](https://user-images.githubusercontent.com/14309871/197917072-efc70fbb-3a37-402f-981b-a75b60ff7561.png)
.

**Comment by billthefarmer** [comment]
See #153, Loading a file that size would break the app. Why people want to use a simple text editor for intended for editing config files etc to attempt to edit enormous files defeats me.

**Comment by Ygarr** [comment]
Let`s look wider. Why not to use simpe, lightweight editor for big files without structure 
and use heavy weight with code highlighting editors for configs to not to make automatic mistakes.
Ok if it is no techical abilities so it is

**Comment by Ygarr** [comment]
Or please expand to 2 Mb or 1.5 Mb it would be enough for 99% of adequate users.

**Comment by billthefarmer** [comment]
The GPL makes it very clear:
> This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

The first line of the [README](https://github.com/billthefarmer/editor/#readme) is also clear:
> Android simple generic text editor. The app is available from [F-Droid](https://f-droid.org/packages/org.billthefarmer.editor) and [here](https://github.com/billthefarmer/editor/releases)

If you want a fancy all singing all dancing text editor please look elsewhere, or else fork this one.

**Comment by Ygarr** [comment]
> The GPL makes it very clear:

Yeah but this not for inter-person relation. It`s just for govs, lawyers. 
Also there nothing about suggestion... like "suggestions or ideas are forbidden". 

BTW, may be fork is the answer. 

You know there 90+% text editors that make me "look elsewhere" but not yours :) The project gives hope.
