### ISSUE TITLE
Feature request: Go to start or end of file

### ISSUE THREAD

**Issue by resolritter** [billthefarmer/editor#181]
Hello and thanks for this app.

I wish the app had the "go to start of file" and "go to end to end of file" features. I sometimes open files with lots of lines and it's cumbersome to scroll all the way to the bottom with the tiny scrollbar.

My current workaround is to search for a pattern that I expect to be at the bottom of the file, which gets me there, but isn't very intuitive.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

![Screenshot_20221116-115436 1](https://user-images.githubusercontent.com/3448386/202174486-8fb10dd5-3cfc-436d-9001-769198e16477.png)

**Comment by resolritter** [comment]
The feature was included in version 1.7.6. Thanks!
