### ISSUE TITLE
Open files as separate tasks on the Recents screen

### ISSUE THREAD

**Issue by gardenappl** [billthefarmer/editor#184]
It might be nice if every text file was opened/created as its own task, with the ability to navigate between them from the system's Recents screen. That would be an easy way to allow editing another file without losing contents of a previous file.

https://developer.android.com/reference/android/R.attr#documentLaunchMode

**Comment by billthefarmer** [comment]
OK, that will be in the next version. There are side effects, the list of recent files will be last updated by the instance which exits last, so may not always work as expected. I don't think this attribute is necessary for this behaviour, but I put it in anyway. It has the effect that opening a file from a file manager will always create a new instance.
