### ISSUE TITLE
Hide word count, character count and character set from toolbar

### ISSUE THREAD

**Issue by smaragdus** [billthefarmer/editor#185]
@billthefarmer 

First, thank you for your excellent editor.

I am using an older version ([1.50](https://github.com/billthefarmer/editor/releases/tag/v1.50)) because the character set and especially the word count and the character count in the toolbar distract me a lot. I would highly appreciate an option to hide the character set, the word count and the character count from the toolbar.

Regards

**Comment by billthefarmer** [comment]
The character set is displayed so no-one accidentally saves a file in [ebcdic](https://en.wikipedia.org/wiki/EBCDIC) or whatever, the word count, etc, was requested &ndash; #125.
