### ISSUE TITLE
No Menu

### ISSUE THREAD

**Issue by jetryco** [billthefarmer/editor#189]
As seen in the image, the "3-dots", where I assume there is a menu, are missing.

![NoMenu_23-01-07](https://user-images.githubusercontent.com/122471391/211865064-bc7c986a-9c5f-4e7d-998b-e4a8f69c4514.png)

It is version 1.79 installed using F-droid on Android 5.1.1 on Samsung Galaxy Note 10 (SM-P600).

**Comment by billthefarmer** [comment]
![Screenshot_20230115-183048 1](https://user-images.githubusercontent.com/3448386/212560056-61ef8d67-5fcc-4cb8-8c50-915036c9e51c.png)

**Comment by jetryco** [comment]
Ok. My guess is that something changed in the transition Android 5 --> 6.
My problem is that Android 5.1.1 is the last existing update on the unit (SM-P600).

**Comment by billthefarmer** [comment]
OK, this is a Galaxy Nexus 5.1 emulator, works fine.

![Screenshot_1674730807](https://user-images.githubusercontent.com/3448386/214820455-e659b8db-00d5-407c-9f7d-0b0b82b4d286.png)

![Screenshot_1674730822](https://user-images.githubusercontent.com/3448386/214820508-7f0d0c9d-4532-46a2-a7c2-daf763c31b59.png)

**Comment by jetryco** [comment]
Hmm, out of ideas.
I tried to change font size, language, etc., no luck.
I have been poking around in the developer options, turned on showing layout bounderies:
![NoMenu_23-01-26_LayoutBounderies](https://user-images.githubusercontent.com/122471391/214970254-a5c652ab-d46c-41da-8c40-b5942402a58c.png)
It did not give me any useful information, can you see anything?

Is there there something in developer options that can reveal some useful information?
(I do have some programming skills but not on phones/tablets.)

 Anyway, I will try to uninstall/reinstall the app.

**Comment by billthefarmer** [comment]
I don't have any ideas either. Developers don't have a great deal of control over how the toolbar/menu appears on any given device. The content is defined in an xml file &ndash; [Menus](https://developer.android.com/develop/ui/views/components/menus), in this case &ndash; [here](https://github.com/billthefarmer/editor/blob/master/src/main/res/menu/main.xml). There are two functions in the API for this particular menu: [onCreateOptionsMenu](https://developer.android.com/reference/android/app/Activity#onCreateOptionsMenu(android.view.Menu)), used to create the menu, [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L875) and [onPrepareOptionsMenu](https://developer.android.com/reference/android/app/Activity#onPrepareOptionsMenu(android.view.Menu)), [here](https://developer.android.com/reference/android/app/Activity#onPrepareOptionsMenu(android.view.Menu)), used to enable/disable items according to the state of the app, to add checkmarks and to add items dynamically, like the **Open recent** items.

There is a property `android:showAsAction` which is used to indicate whether you would like the item to appear in the toolbar or not, but it is a suggestion, `ifRoom`, which I haven't used in this app. I have had all sorts of weird things reported by users of my apps, most of which I have not been able to reproduce.

**Comment by jetryco** [comment]
I am an idiot... There is no Menu icon, because there is no need. This old tablet has a hardware menu button, and it works.

Thank you for the patience with the stupid.

**Comment by billthefarmer** [comment]
OK, I've had quite a few weird reports, but this is the best one yet.
