### ISSUE TITLE
Handling files that have been modified and more careful auto-saving

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#19]
Could there be checks whether a file has been modified before saving?

* When Editor is un-paused, it could check if it is still showing the current version of the file and prompt for a reload if it is not.
* When the user tries to save or Editor wants to auto-save, it could check if the file has been modified before overwriting it and ask for confirmation.

Use case: I am editing text files that are synchronized between my phone and computer. Only after losing data several times, I noticed that Editor was overwriting my changes with outdated data.

**Comment by billthefarmer** [comment]
You have flagged up a bug, which I had missed, that the auto-save function doesn't check if the user has modified the file before saving it. I will look at this. In order to achieve it the app will take note of the last modified date of the file when it loads it, and after it has saved it. It will check that date again before saving and after the app has been paused.

**Comment by billthefarmer** [comment]
Ok, that is in the latest version.

**Comment by Markus00000** [comment]
That was fast, thank you. Appreciate your excellent work and how responsive you are.

**Comment by monolifed** [comment]
One can also use the hash(like sha1 md5) of the text file to check for modifications.

**Comment by Markus00000** [comment]
@billthefarmer Do you think the auto-save feature should be optional? Personally, I’d like to disable it. If I accidentally modify a file or want to discard my changes, I’d intuitively press the back button. Having the file auto-save in this scenario would surprise (and annoy) me.

Is the reason for the feature to exist in the first place to prevent data loss when Editor is killed while being in the background?

**Comment by billthefarmer** [comment]
This was added because it was requested in #13. I will look at this. I can change the logic to always ask before saving, and move the function to `onStop()` rather than `onPause()` so that it only happens if the app is killed.

**Comment by billthefarmer** [comment]
Well that didn't work! I have added an auto save option which does.
