### ISSUE TITLE
[Feature Request] Allow select/copy/share in read-only mode

### ISSUE THREAD

**Issue by rai42** [billthefarmer/editor#191]
I frequently use the Editor to open files and copy/paste or share text to other apps.

Since read-only mode is active by default (which is good), it would be nice if the select, copy and share functions would work in read-only mode, so one doesn't have to activate edit mode just to copy text.

Thanks a lot for your work by the way!

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by rai42** [comment]
Thanks a lot, that was quick!
