### ISSUE TITLE
simple Theme for eReader (eInk-Display)

### ISSUE THREAD

**Issue by Mae72DE** [billthefarmer/editor#194]
I like to use the Editor to write on my Meebook P78 (Q78 Android 11) but can't see all Symbols/Buttons on upper line.
I miss a real simple Theme for eInk-Screen for the modern eInk-Tablets (Android-NoteTakingDevices/PDAs).
Can I define my own Theme?

**Comment by billthefarmer** [comment]
To add or change a theme you would have to fork this repo and build your own version. The toolbar in the android standard themes and the custom themes in this app is white icons/text on very dark grey. To change the action bar (toolbar) style you need to dive deeper into the style system as in my [Crossword](https://github.com/billthefarmer/crossword/blob/master/src/main/res/values/styles.xml#L60) app.

**Comment by billthefarmer** [comment]
Would a theme like this work better?

![Screenshot_20230227-102623 1](https://user-images.githubusercontent.com/3448386/221539463-1745b939-cf53-487d-8148-9a8b472f0acd.png)

**Comment by Mae72DE** [comment]
I think most eInk-Screens will just use 15 Gray-Scale Levels - even if that's no 2^x - nor? Well, maybe 16!
And even modern screen can use 256  Shades of Gray, but mostly in a private way … 

... let's stay Serious from 9 to 16, if we be in the office an an App mimik a TypeWriter ...

I'll throw the picture on an eReader - and yes, this seems to work ...

**Comment by billthefarmer** [comment]
OK, that's in the next version

**Comment by Mae72DE** [comment]
Sorry: I try it also on an older eReader, and now I think the Counters (for Words and Lines/Chars) should be darker.
And a real Black and White solution could be the best for this kind of Devices - if the eInk-Android hits more in the marked.

**Comment by billthefarmer** [comment]
OK, I've made all the text black. That will be in another version.
