### ISSUE TITLE
Bug: On Android 6.0, keyboard not even showing up from version 1.81 onwards

### ISSUE THREAD

**Issue by barkoder** [billthefarmer/editor#195]
Keyboard works on 1.80 though.

Thanks!

**Comment by billthefarmer** [comment]
I can't reproduce that. I have checked on four different devices, including one running android 6.

**Comment by barkoder** [comment]
Keyboard Not Working from 1.81 onwards. Version 1.83 shown here in the screen recording. All I see is a teal line. Tapping on it doesn't do anything. Changing to a different keyboard also doesn't do anything.

https://user-images.githubusercontent.com/70430094/224515431-583da549-1734-4a20-802a-d8c3ddb69cbf.mp4

--------------------------------------

Keyboard Working fine on 1.80

https://user-images.githubusercontent.com/70430094/224515442-050d57a3-5545-454a-902d-50eaa859faaa.mp4

**Comment by billthefarmer** [comment]
The only change in version 1.81 was to make the text selectable in view mode. Also there is a [bug in android 6](https://issuetracker.google.com/issues/64285636) which causes using `Activity.recreate()` to crash the app. It is necessary to use this function to change theme, change the app mode, etc. Therefore to switch to edit mode, you need to rotate the device to force the activity to be recreated. Another option is to use the **Options=>View files** item in the menu to open files in edit mode.

**Comment by barkoder** [comment]
The `Options=>View files` option was already ticked, and the keyboard doesn't show up(in portrait) regardless of whether or not that option is ticked.

However rotating the phone, tapping the text, and rotating it back to portrait works.

Thank you @billthefarmer for the help.

From what you've said, it appears like this isn't fixable on your end.

I guess I'll be sticking with 1.80. Let's hope I don't need any feature after 1.80.

I don't know if closing this issue is appropriate, so you feel free to close it, if you feel it can't be fixed.

Thanks!
