### ISSUE TITLE
Clone of your app in Google Play

### ISSUE THREAD

**Issue by marcoXbresciani** [billthefarmer/editor#196]
Hello,
  just like mine (https://codeberg.org/marco.bresciani/TKCompanionApp/issues/24), I've found the same person has also cloned your app in Google Play.
See https://play.google.com/store/apps/details?id=org.billthefarmer.edoter

I wrote Google for copyright violation and they replied they are going to remove the clone of my app.
Feel free to do the same.

**Comment by kamil-cy** [comment]
Hi,

I see that under https://play.google.com/store/apps/details?id=org.billthefarmer.edoter the page says not found, so I guess this issue can be closed.
