### ISSUE TITLE
Opened file can not be saved after edit

### ISSUE THREAD

**Issue by iamgitcat** [billthefarmer/editor#197]
App is 1.83 from F-Droid. Open any text, press save icon = error.
![Screenshot_20230326-003001](https://user-images.githubusercontent.com/83538283/227743287-f16de121-0f18-46c8-b456-8b927f8805e8.jpg)
It has permissions, if I choose to save and change file name it saves it.

**Comment by iamgitcat** [comment]
I found why it happened. If I open app itself it contained the text from a file I deleted before. Probably tryed to safe that file too? I closed all opened files and now everything works fine.

**Comment by billthefarmer** [comment]
Android apps don't generally give write permission when they share files. My apps don't because the file is in the app's private storage. Editor attempts to resolve content Uris like the one above, but if can't then writing to it will generally fail.
