### ISSUE TITLE
Possibility to open last opened file on application start instead of hard-coded `Documents/Editor.txt`

### ISSUE THREAD

**Issue by kamil-cy** [billthefarmer/editor#200]
Hi,

I would like to drop an idea to add a possibility to open last opened file on application start instead of hard-coded `Documents/Editor.txt`. This could be toggled under `Options` drop-down menu. It would save me (and probably many more people) few taps while using this app. @billthefarmer What do you think about this?

**Comment by billthefarmer** [comment]
OK, that will be in the next version

**Comment by kamil-cy** [comment]
Great, thx.

**Comment by kamil-cy** [comment]
New feature works like a charm, thank you.
