### ISSUE TITLE
[feature request] save as encrypted file

### ISSUE THREAD

**Issue by gbdomubpkm** [billthefarmer/editor#202]
It would really be a plus if we could save the files we want as encrypted files. The decryption key provided to open the desired file.

I use another simple text editor under another operating system (Ubuntu Touch) which does this very well.

![screenshot20230502_110852444](https://user-images.githubusercontent.com/50362604/235629118-16f17cdc-dea5-47d9-aeaf-d8f1d403c5fe.png)
![screenshot20230502_111330327](https://user-images.githubusercontent.com/50362604/235629123-319f5723-f0d2-42df-90c4-35ab8eb86c12.png)

**Comment by billthefarmer** [comment]
I know enough about encryption to know that I don't know enough to implement a secure system. There are plenty out there who think they do. I also don't want to get involved with the inevitable issues over lost passwords.

**Comment by gbdomubpkm** [comment]
For the lost password, it's the user's problem, not yours at all.
I understand very well that you feel that you don't know enough at the moment to implement something secure.
However, if one day it can be done it will be good. It is always better to be able to secure access to files.
Do you know a simple non-intrusive app that encrypts / decrypts text files on android?
