### ISSUE TITLE
Missing filename on shortcut when restarting phone

### ISSUE THREAD

**Issue by j0hann3s** [billthefarmer/editor#207]
The new shortcut feature is awesome! Just found the minor bug that the shortcuts lose their set names and get the name "Editor" after restarting my phone.

**Comment by billthefarmer** [comment]
That doesn't happen on any of my devices. Once the app has created a shortcut what happens after that is down to the launcher and android. They get deleted if you uninstall the app.

**Comment by j0hann3s** [comment]
Interesting! So my launcher (I use GrapheneOS) then renames widgets on restart. Thanks for clearing that up, looks like I will have to remember the position instead 😂👍
