### ISSUE TITLE
[Bug] Cannot open editor from other apps after updating 

### ISSUE THREAD

**Issue by MUTED64** [billthefarmer/editor#211]
## Environment 
Device: Redmi K50
OS: MIUI 14.0.7 (Android 12 TP1A.220624.014)
App: version 1.88 from F-Droid

## Description 
The issue pertains to the behavior of the editor when attempting to open files from other applications. After updating to version 1.88, when trying to open a file from another application, the editor briefly opens for a split second and then immediately returns to the original application without actually opening the file in the editor. This behavior is consistent and occurs every time I attempt to open a file from an external source. The problem is not specific to any particular file type or source application.

## Steps to Reproduce
1. Use the latest editor app.
2. Open any file in another application (e.g., file manager, email client).
3. Select the option to open the file using the editor.
4. Observe the behavior of the editor.

**Comment by billthefarmer** [comment]
I have released a new version with a fix

**Comment by staticpiratex** [comment]
I can't find the fixed version on F-Droid, I can find only the 1.88 with this issue

**Comment by staticpiratex** [comment]
> I have released a new version with a fix

I can't find the fixed version on F-Droid, I can find only the 1.88 with this issue

**Comment by billthefarmer** [comment]
We have to wait for F-Droid to build it &ndash; can take a week or so.

**Comment by staticpiratex** [comment]
> We have to wait for F-Droid to build it &ndash; can take a week or so. Edit: see #212 for temporary fix.

I checked now the F-Droid and I can download the latest version without the issue. Thank you for response!

**Comment by MUTED64** [comment]
Thank you for the quick fix.
