### ISSUE TITLE
DISCARD saves changes anyway

### ISSUE THREAD

**Issue by arschficken** [billthefarmer/editor#22]
In Editor 1.09, open a file, make a test change, then attempt to close the app (e.g. using ◁). A dialog with two options, CANCEL and DISCARD, appears. CANCEL closes the dialog. DISCARD *saves* changes, then exits.

This may be related to bug #10. Ideally the dialog should, as @Markus00000 suggested there, offer both a DISCARD and a SAVE option. I don't personally care about CANCEL if the app remembers which file I was editing and my position in it, since in that case nothing is lost by quitting. Either way, DISCARD shouldn't save.

**Comment by billthefarmer** [comment]
This is due to unintentional side effect of save on pause which someone asked for. It is simple to fix.
