### ISSUE TITLE
Change Heading Colour

### ISSUE THREAD

**Issue by meganleewebb** [billthefarmer/editor#226]
Heading colour is dark blue. Hard to see on black, dark, and retro theme. 

How about yellow? 

I tried testing to find what colours are used. Seems like 
cyan (indented lists and code blocks) and magenta (bold, italics and underline)

![Screenshot_20240219-154045_Editor.jpg](https://github.com/billthefarmer/editor/assets/1691510/51a1afad-9994-4794-9b0d-4caf76e6f382)

![Screenshot_20240219-154130_Editor.jpg](https://github.com/billthefarmer/editor/assets/1691510/683ec715-4dfe-4ba2-bb81-c818e5944cbc)

![Screenshot_20240219-154214_Editor.jpg](https://github.com/billthefarmer/editor/assets/1691510/26331146-7281-48d3-907d-c6c80ca9b7b0)

**Comment by billthefarmer** [comment]
I think it shows up quite clearly. I can't use yellow because that is the highlight colour for search.

**Comment by meganleewebb** [comment]
![Screenshot_20240221-044905_Editor.jpg](https://github.com/billthefarmer/editor/assets/1691510/4748783d-9e6d-4346-b9cd-8781e33c2ec5)

How about using #E48744 or similar?

**Comment by billthefarmer** [comment]
I can't see any difference between that and previous.

**Comment by meganleewebb** [comment]
My error. 

![Screenshot.jpg](https://github.com/billthefarmer/editor/assets/1691510/c41b4944-9516-4e6e-b836-23642767dc1c)

How's this look?

**Comment by autumngray** [comment]
FYI, when doing a search under the dark/black theme: yellow highlight + white stroke color is very hard to make out. You might want to adjust the yellow or use black stroke color.

![Screenshot_20240314-073852](https://github.com/billthefarmer/editor/assets/1283495/875c07e0-8de1-4ec1-bcab-ba2efd4cf257)

**Comment by billthefarmer** [comment]
The search highlight colour has to work against all themes and all syntax highlight colours. Because syntax highlighting changes the text colour and search highlighting changes the background you can't mix the two.
