### ISSUE TITLE
Problems with the pinch and expand gestures (to change text size)

### ISSUE THREAD

**Issue by jaimet** [billthefarmer/editor#227]
I'm having problems with the pinch and expand gestures to change the text size. The pinch gesture seems to keep shrinking the text size even when I stop pinching, and I can't get the expand gesture to work at all. Apologies if this is "user error", but I just want to this problem logged before I run out of time tonight.

**Comment by billthefarmer** [comment]
If you have a large text file, because of the time spent resizing, that will happen. The double tap and swipe gesture is easier to control. I will investigate reducing the sensitivity.

**Comment by jaimet** [comment]
I'm still seeing this in version 1.96 (text file size approx 6kB). Have you closed this because the code has changed since I opened this, or because you can't reproduce this? (I can't find anything in the changelog that mentions this.) TIA, J

**Comment by jaimet** [comment]
And FWIW, I've just installed version 1.96 on a different phone and I'm getting exactly the same problem: "pinch in" reduces text size, but "pinch out" does not increase text size (and my text file consists of four words - one word on each line).
