### ISSUE TITLE
Theme change not applied until after exit

### ISSUE THREAD

**Issue by arschficken** [billthefarmer/editor#23]
Changing the theme is not instantaneous, but only takes effect when the app is exited and reopened. If this is intentional (e.g. for simplicity of implementation), there should be a popup explaining it, otherwise the Law of Least Astonishment is violated.

**Comment by billthefarmer** [comment]
This only happens on Android 6, due to a bug in the recreate() function. There is a mention in the release notes for [Version 1.03](https://github.com/billthefarmer/editor/releases/tag/v1.03)

**Comment by arschficken** [comment]
No problem then, it's not a major bug anyway.
