### ISSUE TITLE
Scrollbar inconsistency in view/edit

### ISSUE THREAD

**Issue by clach04** [billthefarmer/editor#232]
In View mode for both Editor and https://github.com/billthefarmer/notes (which I think is using Editor as a sub-component?) there is a scrollbar which can be used.

In Edit mode, this appears to only show the location and is not usable. In Editor, a workaround is to use the "Go To..." which is vaguely similar to a scrollbar implementation.

**Comment by billthefarmer** [comment]
The scrollbar doesn't work &ndash; see https://github.com/billthefarmer/notes/issues/51#issuecomment-2056799971
