### ISSUE TITLE
enhancement idea: reverse search

### ISSUE THREAD

**Issue by clach04** [billthefarmer/editor#233]
Incremental forward search works great. It would be a useful feature to be able to search backwards.

It looks like repeating a search will loop around which is a semi-workaround for small files but not realistic for files with many matches. As there is a file size limit it may be reasonable to search the entire document and also include a count. E.g. 1 of 35 hits.

**Comment by billthefarmer** [comment]
Find previous doesn't work &ndash; see https://github.com/billthefarmer/editor/issues/225#issuecomment-1959193868
