### ISSUE TITLE
Make text files open in view mode by default

### ISSUE THREAD

**Issue by shadowbone94** [billthefarmer/editor#25]
This is an enhancement opinion.
If you could make the app to open text files in view mode, where you can view the notes simply by scrolling. And then add an option to edit the document inside the menu toolbar. 
This is because sometimes I only need to view the documents and accidental touch on a line invokes the keyboard which I  have to dismiss every time.

**Comment by billthefarmer** [comment]
I will investigate this.

**Comment by doronbehar** [comment]
I wanted to open a similar feature request and stumbled upon this one.

What I originally thought of was that when opening a text file say from a file explorer, there will be 2 activities (I hope it's the right key word) to choose from - one for read only and the other with editing enabled.

**Comment by billthefarmer** [comment]
It's possible to set the input type to 'none' to prevent editing initially, and then set it back to normal on a long touch on the view, which will also select some text. I haven't got around to testing that yet.

**Comment by billthefarmer** [comment]
Yes that worked, it's in the [next](https://github.com/billthefarmer/editor/releases/tag/v1.11) version. A long press on the view sets it back to normal, or changing almost anything on the menu. It will be in edit mode until another file is loaded.

**Comment by shadowbone94** [comment]
@billthefarmer Tried the updated version. The function works fine, although I had hoped the feature to edit could have been integrated into the options menu instead of long press. But its alright, it serves the purpose anyway. Thank you. :smile:

**Comment by billthefarmer** [comment]
Well the logic is you don't need a menu item to make it initially read only because it is by default. And you have to touch the view to edit it and trigger the keyboard, so a long touch is a small step for the user. if you don't want to select any text, touch a blank area.

**Comment by Markus00000** [comment]
I thought the new version was broken until I read #31 and learned about long-pressing. It was not intuitive for me.

At least in the past, LibreOffice used an icon to indicate a view-only mode. Would adding an icon to toggle view/edit modes be justified? I think I would use it more often than the icons for search and open file.

**Comment by billthefarmer** [comment]
OK, I concede defeat. I have added an edit icon to the latest version.

**Comment by msteudtn** [comment]
Can we reopen this issue again?

In my opinion, this behavior isn't intuitive for an editor. Common use case should be editing, not viewing - no matter if it's a shopping list, a to-do list, general notes or source code. :)

To enter edit-mode, I can currently either press the edit-button (move my thumb to the top of the long screen) or try the long-press on the pane (a bit shaky in the train or in winter).

Can you please:
* Either enable edit-mode by a short press or a double press (instead of long press)
* Or start the app in edit-mode by default? (not sure if the keyboard shows up right away)

Thank you.
