### ISSUE TITLE
Improving the English translation

### ISSUE THREAD

**Issue by Markus00000** [billthefarmer/editor#26]
Some thoughts regarding the English translation.

##### Dialogs

    <string name="choose">Choose a file name</string>

* I think this should end with a full stop.
* As it’s prompting the user to enter a file name, it might be friendlier and clearer to write: *Please enter a file name.*

In addition, the *OK* button should be labelled *Save* instead.

     <string name="saveAs">Save as…</string>

When used as the title of a dialog, this is usually phrased as a question. For example: *Where do you want to save this file?* or *Where to save this file?*

[Example dialog](https://storage.googleapis.com/material-design/publish/material_v_12/assets/0Bzhp5Z4wHba3UTdrRUZpMjJ2d3M/components-dialogs-usage5.png) from [material.io](https://material.io/guidelines/components/dialogs.html#).

##### Typeface

The typeface options are *normal* and *monospace.* My preference would be *monospace* or *fixed-width* (easier to understand than *monospace*) and *proportional* (because I don’t know of any synonyms).

I think *normal* raises the question what a normal typeface is.

**Comment by milouse** [comment]
For the typeface, I've translated them with correct typography name in french, that is to say : *Sans serif* for « normal » and *chasse fixe* for monospaced. I agree mixing typography (monospace) and generic (normal) term is a little strange.

**Comment by Markus00000** [comment]
Note that fixed-width typefaces can be [sans serif](https://fonts.google.com/specimen/Source+Sans+Pro) or [serif](https://fonts.google.com/specimen/Cutive+Mono), therefore, *sans serif* and *chasse fixe* is mixing terms, too.

**Comment by milouse** [comment]
Right, good catch. It seems « proportional » and « monospaced », i.e. « linéale à chasse variable » and « chasse fixe » in french is the best choice. Or maybe just named the font used (it seems to be roboto sans and roboto monospaced) ?

**Comment by billthefarmer** [comment]
OK, that's easy to fix. The reason for the original names is because that is what they are called in the [API](https://developer.android.com/reference/android/widget/TextView.html#attr_android:typeface).

**Comment by billthefarmer** [comment]
@milouse You have translated 'proportional' as 'linéale à chasse variable' above, but when I look up the French translation I get 'proportionnel', which would appear to be a direct translation. It is also what the big fat Collins Robert dictionary we happen to have says.

**Comment by billthefarmer** [comment]
This gets better. According to Google, the French for 'Monospace' is 'Monospace', but the English for 'Monospace' (French) is 'People Carrier'.

**Comment by milouse** [comment]
Yes, Monospace is related to car in french, not to fonts. There is several words to translate it in french, but « chasse fixe » is the better (see [wikipedia french article](https://fr.wikipedia.org/wiki/Chasse_(typographie)) about it for proof). 

I agree the best translation for proportional in french'd be just « proportionnel ». Linéal and other terms are too nerdy to be used for everyone.

**Comment by billthefarmer** [comment]
@Markus00000 - I don't necessarily completely agree with Google's guidelines on dialogs. Some of the dialogs, such as those requested in #19 are unsolicited and triggered by an unrelated action, such as rotating the device. In that case I have used the app name as the title so the user knows where it's coming from. In other cases I have used the action requested as the dialog title for confirmation. I also think the use of redundant punctuation in short messages in English looks fussy. Question mark or exclamation point - fine, it's saying something. That of course may well be different in other languages.

**Comment by Markus00000** [comment]
Understood. My main issue are generic button labels that don’t state what the button does: yes, no, okay, cancel.

It requires re-reading the dialog whenever it shows up to determine which answer does what. Labels like *Save* or *Discard* are information dense and require almost no context.
