### ISSUE TITLE
About strings: translators

### ISSUE THREAD

**Issue by airon90** [billthefarmer/editor#28]
By now there are just two languages, English and French. Both keep the French translators in About section.

Other languages will be added (#24, #27) so we should clarify if every language should have every translators of all available languages or just the credit for the current language.

If every language should have every translators of all available languages, I think that it will be better to divide About string into more strings and hardcode the translators.

If every language should have every translators of just the current language, the original English key shouldn't have the credits for French translation

**Comment by billthefarmer** [comment]
OK, I think that is a good idea, this was discussed in #26
