### ISSUE TITLE
"Word wrap" should apply immediately

### ISSUE THREAD

**Issue by RigacciOrg** [billthefarmer/editor#29]
It seems that changing the "Word wrap" option will apply only once the program is restarted. I wish to see the mode applied instantly, instead. Or am I missing something?
Using "Editor - Simple generic text editor" version 1.10 from F-Droid, on an Android 6.0 no-brand smartphone.

**Comment by billthefarmer** [comment]
That is due to a bug in Android 6 - see #23. You can rotate the device to change theme or word wrap.
