### ISSUE TITLE
May I request you to implement multi sessions support?

### ISSUE THREAD

**Issue by whitestone8214** [billthefarmer/editor#30]
I think it would be nice if users can open and/or edit multiple documents at the same time, just like QuickEdit or Jota+.

May I request you to implement it?

**Comment by billthefarmer** [comment]
QuickEdit and Jota+ appear to be commercially produced with revenue generated by advertising and 'Pro' versions. I'm just a retired geek who put together a simple editor for editing the styles in a [Diary](https://github.com/billthefarmer/diary) app and then thought it might be an idea to release it as a separate app. I've implemented most of the suggestions I have received, but multiple file editing would require a complete redesign. Of course anyone is welcome to fork it and have a go...
