### ISSUE TITLE
Version 1.11 breaks suggestions

### ISSUE THREAD

**Issue by arschficken** [billthefarmer/editor#31]
Just upgraded to 1.11, ~~copy and paste~~ suggestions in the editor pane are completely non-functional. Tapping and holding the screen does nothing. Works fine in dialogs such as Save as... 

Android 6.0.1

**Comment by billthefarmer** [comment]
Because of the request, see #25, I received, you need a long touch on the pane after loading a file to enable editing and another long touch to bring up the pop up copy/paste/... menu. There could be yet another menu item to enable editing, but I thought a long touch more intuitive.

**Comment by arschficken** [comment]
Long pressing didn't work for me. I got an on-screen keyboard and could edit the file, but the keyboard gave no automatic word suggestions, the copy brackets never appeared, and the paste popup never appeared.

Based on bug #25, I think I hit an edge case. I had Editor.txt open before the upgrade. When Editor 1.11 opened for the first time, it started with Editor.txt open but editing partially working. But when I re-opened Editor.txt, suddenly it was back to the way it used to be (suggestions, copy/paste, etc. all OK). I guess the problem won't recur, but I worry about new and upgrading users.

Is there a way the code could get wedged in the case of an upgrade? What happens when a user does a clean install of Editor, does it start in this partially working mode?

**Comment by billthefarmer** [comment]
There aren't any modes other than view mode and edit mode. The code is very simple. When a file is loaded which happens automatically at startup, if it exists, the [input type](https://developer.android.com/reference/android/widget/TextView.html#attr_android:inputType) gets set to 'none' [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L1284). On a long touch the input type gets set back to edit mode [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L273).

**Comment by arschficken** [comment]
OK, I can reproduce the problem 100% now. (The lack of suggestions, not the copy/paste. I think I was testing that wrong, expecting it to trigger on long press.)

Simply force stop the app. Next time you open it and enable editing by long pressing the screen, the keyboard appears but suggestions are disabled. To get suggestions back, you need to un-check the Suggestions checkbox, then re-check it. It then works fine until the next time the app gets evicted from memory (e.g. by upgrading it or due to memory pressure in the OS).

**Comment by billthefarmer** [comment]
Yes I got the logic inverted, it will be fixed in the next version.

**Comment by phunkular** [comment]
hi there, on f-droid 1.12 version the menu option for suggestions works for me but is inverted. If suggestions are selected then after some time the suggestion bar disappears and vice versa. I thought that this might be related but perhaps it needs its own ticket?

**Comment by billthefarmer** [comment]
I have just tested this, I can't reproduce it. There was a logic inversion bug, as above, which is fixed in version 1.12.

**Comment by arschficken** [comment]
Confirmed resolved in 1.13 from F-Droid.
