### ISSUE TITLE
Crash when opening a text file sent via Telegram

### ISSUE THREAD

**Issue by slyscorpion** [billthefarmer/editor#40]
Hi,

I keep getting a crash when opening text files sent via Telegram.

Steps to reproduce:

1. Have someone send you a text file in Telegram.
2. Select "Editor" as the program to open the file
3. See the application crash

I have a log of the crash:

java.lang.RuntimeException: Unable to start activity ComponentInfo{org.billthefarmer.editor/org.billthefarmer.editor.Editor}: java.lang.IllegalArgumentException: column '_data' does not exist
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2740)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2801)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1548)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6372)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)
Caused by: java.lang.IllegalArgumentException: column '_data' does not exist
	at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:339)
	at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
	at org.billthefarmer.editor.FileUtils.getDataColumn(FileUtils.java:265)
	at org.billthefarmer.editor.FileUtils.getPath(FileUtils.java:388)
	at org.billthefarmer.editor.Editor.resolveContent(Editor.java:1141)
	at org.billthefarmer.editor.Editor.readFile(Editor.java:1120)
	at org.billthefarmer.editor.Editor.onCreate(Editor.java:215)
	at android.app.Activity.performCreate(Activity.java:6861)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
	... 9 more

My phone's OS is MIUI 9 version 8.1.11 (Android version 7.1.1)

**Comment by slyscorpion** [comment]
Oh and I am running version 1.15 build date December 21st 2017 of Editor.

**Comment by billthefarmer** [comment]
This is the same issue as #39. I have released a new version which will prevent the crash but not open the file. Unfortunately F-Droid are having [build problems](https://gitlab.com/fdroid/fdroiddata/issues/1082#note_55290960) and it hasn't been published yet.

**Comment by slyscorpion** [comment]
Oh sorry, didn't know

**Comment by billthefarmer** [comment]
I have uploaded a debug version which may resolve this [here](https://github.com/billthefarmer/editor/issues/39#issuecomment-359256632). Perhaps you could see if it resolves the problem with Telegraph.

**Comment by slyscorpion** [comment]
Hi,

Just downloaded version 1.16 and it didn't crash when I opened a text file sent via Telegram. 

Funny thing is that when opening a text file this way the content of the file is not shown at all. It's shown when I download the file and then open it via Editor.

**Comment by billthefarmer** [comment]
That's because it's just a workaround to stop the crash. Try the debug version and see if it works. If it doesn't the log output might help.

**Comment by slyscorpion** [comment]
@billthefarmer this is the version I downloaded https://github.com/billthefarmer/editor/files/1649861/Editor-debug.zip and tried to open a file sent via Telegram. I only stated the version number as that's what I got in the About menu for the program...

**Comment by billthefarmer** [comment]
You need to enable USB debugging and use `adb logcat` to view the log. There are apps that can read the log, but you need root with recent versions of android. A couple of useful links:
https://stackoverflow.com/questions/16707137/how-to-find-and-turn-on-usb-debugging-mode-on-nexus-4
https://android.stackexchange.com/questions/14430/how-can-i-view-and-examine-the-android-log
The log looks like this if you filter it for FileUtils, otherwise you get loads of irrelevant stuff:
```shell
$ /d/adt/android-sdk-windows/platform-tools/adb logcat | grep FileUtils
01-21 15:11:00.638 17123 17123 D FileUtils File -: Authority: com.simplemobiletools.filemanager.provider, Fragment: null, Port: -1, Query: null, Scheme: content, Host: com.simplemobiletools.filemanager.provider, Segments: [external_files, storage, emulated, 0, Gert.text]
01-21 15:11:00.641 17123 17123 D FileUtils: Path /external_files/storage/emulated/0/Gert.text
01-21 15:11:00.642 17123 17123 D FileUtils: Path /storage/emulated/0/Gert.text
```

**Comment by billthefarmer** [comment]
I have released a new version which should read the content of the file if it can't resolve the URI. However I am puzzled as to why the debug version you downloaded doesn't read the file from Telegram. I have looked at the sources of [Telegram ](https://github.com/DrKLO/Telegram) and [Simple-File-Manager](https://github.com/SimpleMobileTools/Simple-File-Manager) and they both use the same method for sharing files. The URI from the file manager is `content://com.simplemobiletools.filemanager.provider/external_files/storage/emulated/0/Test.txt` and one from Telegram should be `content://org.telegram.messenger.provider/media/storage/emulated/0/<file path>`. There is an app [Intent Intercept](https://f-droid.org/packages/de.k3b.android.intentintercept/) that will show the content when you share a file. Perhaps you could try it and let me know the DATA field.

**Comment by slyscorpion** [comment]
Hi Bill,

Do you have an apk of version 1.17 I could download? Looked in the releases section on GitHub and that only has the source code...

**Comment by billthefarmer** [comment]
Ok
[Editor-debug.zip](https://github.com/billthefarmer/editor/files/1663137/Editor-debug.zip)

**Comment by slyscorpion** [comment]
Hi Bill,

This is what I see in the DATA field when I open up a document sent via Telegram:

content://org.telegram.messenger.provider/media/Telegram/Telegram%20Documents/4_6001096900617438096.txt

Also, the latest debug version seems to open up documents properly as I've opened up a couple of documents that were sent via Telegram with no crashes and the documents' contents shown.

**Comment by billthefarmer** [comment]
That explains why my app couldn't resolve the URI. The app will open the documents, but the method used for sharing using [FileProvider](https://developer.android.com/reference/android/support/v4/content/FileProvider.html) prevents direct access to the actual file except by guesswork. Having seen the URL I can guess that the file is in `Telegram/Telegram Documents/` in external public storage.

**Comment by slyscorpion** [comment]
Let me know if you still need me to try and grab logs via adb or something of the sort...

**Comment by billthefarmer** [comment]
I don't need the logs as you captured the URI. This is another version which should be able to get the file from Telegram with the right path.
[Editor-debug.zip](https://github.com/billthefarmer/editor/files/1664805/Editor-debug.zip)
