### ISSUE TITLE
cursor movement on edge of screen

### ISSUE THREAD

**Issue by olafhering** [billthefarmer/editor#41]
I use this app to write text, then paste it into other apps (web forms, messengers, SMS, ..).  While moving the cursor around I noticed that moving it to/from the beginning of the line is difficult. Likely because that area is less sensitive due to the smartphone cover.

It would be nice if the left (or all?) borders of the shown text start from some pixels away from the screen borders.

**Comment by billthefarmer** [comment]
OK, that will be in the next version.

**Comment by olafhering** [comment]
Thanks, those 8 pixels added in e31b4d9554e7616bb4441899f85e4fa96f45422f are likely ok.
