### ISSUE TITLE
Supported file types

### ISSUE THREAD

**Issue by yourealwaysbe** [billthefarmer/editor#53]
Hi, thanks for the application.

Is it possible to relax the restriction on file types that can be loaded?  When i try to open a file the browser greys out certain files.  Some of these are things such as small data files in text format that it would be useful to be able to open.  However, they are greyed out, presumably because they are not recognised as text. (e.g. gpx files, and .puz files (crosswords)).

**Comment by billthefarmer** [comment]
See #45. If you use a file manager like OI File Manager, it will let you open any sort of file.

**Comment by yourealwaysbe** [comment]
Ok, sorry, i didn't see the previous issue.  I'll close this as a won't fix.
