### ISSUE TITLE
Markdown View

### ISSUE THREAD

**Issue by monolifed** [billthefarmer/editor#6]
An option to view opened file as markdown (like in Diary app) would be nice.

**Comment by billthefarmer** [comment]
It's supposed to be a simple basic text editor, not a panacea for all

**Comment by monolifed** [comment]
I thought it could be useful even if it is a basic text editor.

**Comment by arschficken** [comment]
"Every program attempts to expand until it can read mail. Those programs which cannot so expand are replaced by ones which can." —Jamie Zawinski

By the way, @billthefarmer, your app has quickly become the best text editor on F-Droid. (And I think I've tried them all. Lesser Pad, buggy and lacking inertial scroll, is a distant second.) Thanks for your super coding!

**Comment by billthefarmer** [comment]
Having thought about this, it wouldn't be too difficult. Pass the text through a markdown HTML encoder into a file and send the file to a HTML reader. But I've no intention of reading mail - use emacs for that.
