### ISSUE TITLE
android oreo 8.0 cannot save to external sd card

### ISSUE THREAD

**Issue by th1031** [billthefarmer/editor#65]
I'm unable to create new text files or save edits on files that exist on external sd card. If I understand correctly this may be a function of the restrictive access of the OS. However I am also using a file manager (https://play.google.com/store/search?q=Cx%20File%20Explorer&c=apps) that has a built in but rather rudimentary editor where I can edit and save existing files, though not create new ones (it doesn't have this function). 

I've read the info at:
https://developer.android.com/training/data-storage/files#WriteExternalStorage
and wonder whether your app asks for WRITE_EXTERNAL_STORAGE on installation.
Thanks.

**Comment by billthefarmer** [comment]
The app has the `WRITE_EXTERNAL_STORAGE` permission or it wouldn't work on any version of Android. I don't have a Oreo 8 device for testing. There may be some subtle nuance of Oreo 8 I don't know about, or the app may have lost permission or not been given it on installation. You can check in Settings->Apps->Editor->Permissions. In Nougat 7 it shows Storage. If you try to take it away you get a warning pop-up message. Assuming the app has got the storage permission...

If you open a file from the icon on the toolbar you should get the option of using the built in file manager if there is one, or the one you installed to open a file. What happens if you select a file?
If you can open a file, you can modify it and save it with the icon on the toolbar. What happens?
You can also use the Save as... menu item to save a file with a different name. What happens?
If you select a file in a file manager you should get the option of using Editor to open it. What happens?

**Comment by th1031** [comment]
Yes, the app has storage permissions as you explain it does for Nougat 7.
With respect to opening a file (I'm assuming you mean using a file manager)
I can select in the Cx File Explorer settings whether I want to use the
internal editor. If selected, of course it uses internal. If unselected it
prompts for how to open file. When I select a text file (stored on external
sd card) to view/edit, I see your "Editor" is available and have the option
to set it as the default app. I select your app, open the file, press the
pencil icon to edit, make changes, press the icon that looks like a 3 1/2"
disk, and that icon disappears, leading me to believe the changes have been
saved. But it has not - pressing the back arrow and quitting the file
manager and editing the file again shows changes are not there.

Using the save as option from your Editor I can enter a new filename, but
the file is never created. Using the menu from Cx File Explorer, I can
create a new file, eg. test.txt  and it is created as a zero byte file, but
it cannot be modified using your Editor. If I go back and allow Cx File
Explorer to use its internal editor it can write this file without issue.

If it might be helpful, here is some info from my filesystem:
1|h1:/ $ stat sdcard
  File: `sdcard' -> `/storage/self/primary'
  Size: 21       Blocks: 0       IO Blocks: 512 symbolic link
Device: 2h/2d    Inode: 7641     Links: 1
Access: (777/lrwxrwxrwx)        Uid: (    0/    root)   Gid: (    0/
root)
Access: 1969-12-31 20:00:00.000000000
Modify: 1969-12-31 20:00:00.000000000
Change: 1969-12-31 20:00:00.969999999

But note this is noit my external sd card but rather some part of internal
storage Android calls 'sdcard'.

My external sd card is here:
h1:/ $ stat
/storage/3666-6231/

  File: `/storage/3666-6231/'
  Size: 131072   Blocks: 256     IO Blocks: 512 directory
Device: 17h/23d  Inode: 16       Links: 1
Access: (771/drwxrwx--x)        Uid: (    0/    root)   Gid: (
1015/sdcard_rw)
Access: 2017-01-04 02:07:48.000000000
Modify: 2017-01-04 02:07:48.000000000
Change: 2017-01-04 02:07:48.000000000

Thanks for taking time to look into this.

**Comment by billthefarmer** [comment]
Well, I've found out why...
```shell
12-10 20:11:41.898  2566  2566 W System.err: java.io.FileNotFoundException: /storage/1BE3-3B0A/Editor.txt (Permission denied)
12-10 20:26:19.480  2566  2566 W System.err: java.lang.SecurityException: Permission Denial: writing com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/document/1BE3-3B0A%3AEditor.txt from pid=2566, uid=10062 requires android.permission.MANAGE_DOCUMENTS, or grantUriPermission()
```
It would appear that the file manager hasn't given Editor write permission when it returned the file Uri when the file was opened. There's not a lot I can do about that. It doesn't have to give itself permission to edit the file, which is why it works.

**Comment by th1031** [comment]
@billthefarmer ...
I'm able to report when using the Android Oreo 8.0 stock file manager (not very cleverly hidden as the Downloads App) I am able to associate your Editor with .txt files and save changes to existing files on my (removable) external sd card. 
https://www.computerworld.com/article/3221287/android/android-file-management-an-easy-to-follow-guide.html

Perhaps this is because it is the Downloads app which has the write permissions on this storage, I don't really know. Sadly I cannot use either your app or the Downloads app to create a new file on this media. But I have a workaround whereby another app can create the file, then I can come back and edit as explained above.

Your Editor allows saving (new) files only to some portion of my internal storage set aside as writeable for installed apps. I guess if I had no external sd card, I would appreciate that - so I understand the need to program that way.  Yet it strikes me as unreasonable that on installation, an app such as yours cannot query the user for permission to write to "true" external storage if it detects it's presence. It seems when the OS now asks for such permission, that permission is not for removable external storage, but the internal storage it is now calling external. Or is it? 

Can't this be used?
/* Checks if external storage is available for read and write */
fun isExternalStorageWritable(): Boolean {
    return Environment.getExternalStorageState() == Environment.MEDIA_MOUNTED
}
... go on to save file

I'm not an android programmer, and my further reading at:
https://developer.android.com/training/data-storage/files
seems to reveal there are limited options for how to save a file on mounted external storage.  It seems to want only predefined media types like audio, photos, video.

Anyhow, I can use Editor with some workarounds, so thanks!

**Comment by th1031** [comment]
Hi - yes - comment on your update re convert to internal.
Personally I'm not sure about converting external sd card to internal storage. I'd have to understand whether that means apps (maybe) or even some critical part of the OS (unlikely, imo) would start writing there. Could be considerable grief if it failed.

**Comment by billthefarmer** [comment]
I've looked at this on an emulator. Initially the SD card works like a USB stick, you can put stuff on it and move it between devices. If you convert it for internal storage then you can move data back and forth. You can also store apps on it. All my apps have that option. You can still eject it, etc.

![image](https://user-images.githubusercontent.com/3448386/49787588-f705d180-fd1e-11e8-94ca-cf028573e99f.png)

**Comment by th1031** [comment]
After reading this, I'll take a pass for now. My phone has no simple button press to format as internal and there is no current, compelling reason to do so - internal storage is sufficient.
https://www.androidpit.com/how-to-format-microsd-cards-as-internal-storage

Not that I need a simple button press as I've been a linux user since the pre v 1.x kernels. I'd simply prefer to manage files however I want rather than how the OS deems to be correct and I don't want to spend endless hours 'tweaking' in order to do so. Perhaps this is the dumbing down of Android so 5 year olds can use it without breaking anything. At some point there will be viable alternatives to iOS and Android - I look forward to the develpment of eelo, pmOS and others. Thanks for your app Bill!

**Comment by SmilingHorse** [comment]
@th1031 Formatting as internal storage repartitions the sd card and encrypts the file system so you'd be able to store apps on without worrying someone modifies them. More on that here: https://nelenkov.blogspot.com/2015/06/decrypting-android-m-adopted-storage.html

**Comment by th1031** [comment]
Thanks - that's an interesting article from which I'll take some notes.
Apparently however, whether this procedure is available depends on phone
model/manufacturer. After reading the article I see little reason not to
format as internal storage, especially if free space on internal storage is
scarce. I'll have to backup my sd card and check iit out when I have more
time.
