### ISSUE TITLE
Cannot open file explorer, get "No apps can perform this action"

### ISSUE THREAD

**Issue by anonymous73** [billthefarmer/editor#66]
Hi guys, great software. This may not be so much a problem with your software, but you might be able to bolster the software against my problem.

I may have disabled a service (and cleared the data of said service) on my new phone in the hope of improving the battery life and privacy of my device.

When I click the Folder button in the top-right a message pops up on my screen. The heading is "Choose an action" and the body says "No apps can perform this action". The 'My Files' service works fine, so I know that is not the problem. What else could be stopping my device from using the 'My Files' interface from selecting the file.

I have disabled most of the Google and Samsung apps that could be disabled after doing research on whether I need their functionality, including Google Play Store. 

I have KitKat running.

Any help would be vastly appreciated.

**Comment by billthefarmer** [comment]
I don't think KitKat comes with a built in file manager, so there's no file picker. You need to install one.

**Comment by anonymous73** [comment]
Thanks for your lightning fast reply Bill.

I do have a File Manager on my new device it seems. It is quite slick actually, must be new to Kitkat because I didnt have it in Jellybean. I was able to trigger it from my non-native email program when adding an attachment. I was also able to use this file manager in another app when selecting a file to process. So it seems to be something related to Editor.

**Comment by billthefarmer** [comment]
I've tested this with an emulator - KitKat 4.4.2 - android-19. There isn't a file manager, but there is a file picker, but you have to enable access to the sdcard. The empty .mp4 files were an attempt to capture this with `screenrecord` which wouldn't work.

![ed1](https://user-images.githubusercontent.com/3448386/51848564-b9ccc180-2315-11e9-8b94-b8b339a482e9.png)
![ed2](https://user-images.githubusercontent.com/3448386/51848565-ba655800-2315-11e9-966a-c56bc62ffe6c.png)
![ed3](https://user-images.githubusercontent.com/3448386/51848566-ba655800-2315-11e9-892b-30b5675ac15c.png)
![ed4](https://user-images.githubusercontent.com/3448386/51848568-ba655800-2315-11e9-95a4-432f29a610f4.png)
![ed5](https://user-images.githubusercontent.com/3448386/51848569-bafdee80-2315-11e9-8a87-8851ea5eb707.png)

**Comment by anonymous73** [comment]
Hmm. Ticked those and reset my device. The File Picker seems to work in those other two non-native programs but not for Editor. The only thing that i can think of that could be different in this case is, are you in anyway trying to limit the filetype to be opened/openable to a mime type. If so, have I disabled some kind of mime-type selector app?

**Comment by billthefarmer** [comment]
It's using a mime type of `text/*` to attempt to open a file with some sort of text in it. The code is [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L110) to define the mime type and [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L1151) to open the file picker. The reason for specifying text is to avoid opening binary files because the app reads files assuming they are text and might corrupt them. The images and video files were greyed out in the last screenshot.

**Comment by anonymous73** [comment]
I'm not an expert coding apps by any means but it was interesting to have a look at some of the code. in the setup i am guessing that you somehow registered the fact that ypur program can open all the different text files yes? Would you happen to know where this info might be stored?

Even if you know where it is installed there's a chance I will not be able to see this file, because the phone is not rooted. If for some reason the data from this file is missing "Editors" ability to open such files, should do you think attempting to reinstall is a good idea?

Also could moving the program onto the SD card have broken some aspect?

**Comment by billthefarmer** [comment]
The links are gave you above are all there is, except the code for reading the file that the filepicker returns. That's [here](https://github.com/billthefarmer/editor/blob/master/src/main/java/org/billthefarmer/editor/Editor.java#L666). Android only uses mime type, it's up to the file picker to interpret file extensions. There's not a lot of consistency between file managers.

**Comment by anonymous73** [comment]
Its nice to read your code, I didn't know that a long press puts the state into Edit mode. Useful. Another program I used in the past used a double-tap and so i have been in the habit of double-tapping to no effect, but I digress.

I have yet to read the code fully. 

I did try some ideas i mentioned earlier to no effect. Idea 1 being moving the software back to the SD card and clearing the cache, idea 2 is clearing the cache and data and reinstalling. Both did not work. 

What updates have you installed on your emulator? My installation says I am up to date ie. Updated but now I'm having second thoughts. If i have disabled Google Play and Samsung App stores, does that Update feature in the settings area function correctly?

**Comment by billthefarmer** [comment]
I still don't understand your problem, it's not reproducible on any of my devices or emulators. I forgot to say that the app can be installed where you want, by request, the entry in the manifest for that is [here](https://github.com/billthefarmer/editor/blob/master/src/main/AndroidManifest.xml#L6).

If you use `Save As` to save a file, it is added to the list of recent files, I just checked that.

**Comment by anonymous73** [comment]
Okay, the fact that I can perform a Save As  is something positive as a get around, cheers.

Yeah, it's a hairy one. I'm going to try something over the next week or so. Keep it open, so if I do solve it I can share the result. 

Thanks a heap for your assistance to date.

**Comment by billthefarmer** [comment]
I did a bit more research on this, I tested on an Jelly Bean 4.2.2 - android 17 emulator. There is definitely no file manager. I tried my Diary app and got the choice of  music or images. If you install a file manager you get that as well.

![screenshot_1549019143](https://user-images.githubusercontent.com/3448386/52121144-7d031200-2616-11e9-9360-b81765c2b71e.png)
![screenshot_1549020845](https://user-images.githubusercontent.com/3448386/52121145-7d9ba880-2616-11e9-8e6b-c399edf74df9.png)
![screenshot_1549021275](https://user-images.githubusercontent.com/3448386/52121147-7d9ba880-2616-11e9-8eab-87c406ed7d17.png)
![screenshot_1549021145](https://user-images.githubusercontent.com/3448386/52121146-7d9ba880-2616-11e9-872e-458d7826c9e0.png)

**Comment by anonymous73** [comment]
Thanks Bill,

 I'm running KitKat however that is the same message I get. 

It really isn't too big a headache, do you think you might consider adding a file to the top of the 'Open recent' list on an ordinary Save or do you think that might conflict with people's expectations? It is 'open recent' not 'Open recently opened'.

I was also thinking about the long tap to toggle the Edit mode. Long tap is normally reserved for selecting text so someone who wishes to only copy text without editing the text cannot do that without going into Edit mode. I feel like perhaps double tap is better suited to toggle Edit mode after all. Do you think users would be confused by a change like this though?

**Comment by anonymous73** [comment]
I may give up on solving the OP. I would like to manually update to the latest software without going through Account Management and Resistration with Samsung and/or Google but it doesn't seem possible. I'm having difficulty even working out whether this installation really is the most updated it can be. The Update feature says its up to date, but it seems wrong to me, to not have an update for so long. I'm not at librrty to give particulars unfortunately.

Thanks again.

**Comment by billthefarmer** [comment]
If you want a Google/Samsung free phone your best bet would be to install [LineageOS](https://www.lineageos.org), [Pixel Experience](https://download.pixelexperience.org), or something similar. It's plain vanilla Android without the bloat, and if you don't want Google apps, don't install them. If your phone is supported you will probably get a more up to date version of Android.

**Comment by anonymous73** [comment]
I may just.

**Comment by anonymous73** [comment]
If you want me to open the long-tap vs double-tap issue as a seperate ticket for wider debate I would be open to that.

**Comment by billthefarmer** [comment]
Double tap is also used for selection, possibly in later versions. I don't think read only, but selectable is a valid input state in Android, or if it is, it's well hidden.

**Comment by anonymous73** [comment]
That's actually a good point, it might be good to listen for the double tap and use it to select the text.

**Comment by anonymous73** [comment]
Btw, in case you are not subscribed I have published a possible logo enhancement to the other thread.

**Comment by anonymous73** [comment]
I have done a lot of work to fully update the devise, in fact I may apply for a job with Samsung now, haha.

Yes, it doesn't matter how up-to-date the firmware is, one will need to use some other third-party file management system if they want to open a text file in KitKat.

I can safely say I have tried all the native options available. Don't feel bad either it was not this program that compelled me to become an Android Engineer, haha.

**Comment by anonymous73** [comment]
"...one will need to use some other third-party file management system if they want to open a text file ***through this program*** on the KitKat OS."
