### ISSUE TITLE
Icon improvement

### ISSUE THREAD

**Issue by anonymous73** [billthefarmer/editor#67]
I am considering donating some time to making a nice simple icon for your app.

I have graphic design experience but this would be my first app icon.

The look I am thinking of adopting would be mid-low contrast, soft but playful, low-intensity color, with the simple gradient shadow (from a light source in the top left corner).

Here are two examples of the look and feel:
 - https://f-droid.org/en/packages/pro.rudloff.openvegemap/
 - https://f-droid.org/en/packages/org.sufficientlysecure.keychain (I actually think this one is a bit too low contrast, ie. part of the key blends into the green background)

If this proves successful, I may have ways to improve the UI within the program also.

**Comment by billthefarmer** [comment]
I'm quite happy with the icon for this app, unless someone comes up with something stunning. There has been quite a bit done on the UI due to various suggestions, if you look at closed issues - #35, #34.

**Comment by anonymous73** [comment]
Yes, if I do the icon, I will aim to exceed expectations.

The additions to the UI would be cosmetic. UX more than UI. Maybe the choice of some extra font/themes, maybe the ability to specify a theme different to the default with some kind of smart syntax at the start of the file? Nothing too overwhelming but things people can appreciate when they use this editor. So a notepad related to the kids can have a playful border, something for the construction site can look different to the gardening notes etc. I have done some software development in Java in the past, it would not frighten me to code, but I'm a stickler for best practices so I tend to do research before doing something I'm not sure of. This means I work slower than most people, fine when you are donating your time, right?

**Comment by anonymous73** [comment]
If you like it.
![editor_icon](https://user-images.githubusercontent.com/46677800/52143565-d23d3300-26ab-11e9-932d-66104d9b3929.png)

Icon on the retro theme, if you must have an icon, my preference would be to simply have the filename in a bold retro font. If we can find one thats copyleft.

**Comment by anonymous73** [comment]
Retro theme
![editor_icon__retro](https://user-images.githubusercontent.com/46677800/52143818-6a3b1c80-26ac-11e9-84da-c7c825bf52e4.png)

**Comment by anonymous73** [comment]
Looking at it on the device, I could make the pencil a little bit smaller. Up to you. Look at it on a few backgrounds and give me your thoughts.

**Comment by anonymous73** [comment]
![notepad](https://user-images.githubusercontent.com/46677800/52164290-fa29a680-273e-11e9-9cc2-44586a42d183.png)

![notepad_retro](https://user-images.githubusercontent.com/46677800/52164295-07df2c00-273f-11e9-8f3e-65681772ab0d.png)

**Comment by billthefarmer** [comment]
Thank you.

**Comment by anonymous73** [comment]
Np.

I realised that the program remembers where the cursor(?) was in the file. If the program remembers this then it might not be a big stretch to remember a specified, custom (non-default) theme for a document also (forget about the special syntax I mentioned previously).

If you are interested l might in the mid-to long-term develop some ultra light-weight (storage-space conscious) themes. Perhaps it might be something to work on at the same time as the bug that ignores the theme when the phone in put into landscape mode. I'll leave the decision to you how you think it best to proceed.

A

**Comment by anonymous73** [comment]
Hi Bill, I noticed that there is an update for Editor (I almost got a heart attack when I saw the commit about rendering HTML but then I saw the commit and it was simply **writing** valid HTML).

Do you think you will use the new icon that was gifted to the project, or are you waiting for to something specific to apply the icon at such a later time, or do you think the icon is not correct for the project?

**Comment by TacoTheDank** [comment]
@anonymous73 Also is it adaptive?

**Comment by anonymous73** [comment]
Hi Taco,

What is adaptive? I supplied two PNG files that I understand were encoded in the PNG-24 format with no interlacing. 

Have I made a mistake? If so I'd be happy to learn more, just point me in the right direction.

**Comment by TacoTheDank** [comment]
No mistake made, delicious info here: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by anonymous73** [comment]
That's an interesting read, no i have not done a custom background for the icon for parallax effects. I did not even know that was a thing. On this occasion I just want to keep things simple so Bill can easily replace the icon, if he likes it.

**Comment by TacoTheDank** [comment]
gotchu :)

**Comment by anonymous73** [comment]
I'm assuming that Bill didn't use adaptive icons. Did you, Bill?

**Comment by TacoTheDank** [comment]
I've used the app before, it's not adaptive. One can also tell from the `res` folder: https://github.com/billthefarmer/editor/tree/master/src/main/res

**Comment by billthefarmer** [comment]
I don't attach a great deal of importance to the icons of my apps. Once I've got a suitable one I tend to stick with it. The app icon only appears in the launcher. The original image for this one is [here](https://github.com/billthefarmer/editor/blob/master/ic_launcher.png).
![Editor](https://github.com/billthefarmer/editor/raw/master/ic_launcher.png)
Notice the subtle shading and transparency, making up a 512x512 rectangle. The original image for an app icon needs to be about this size, because the legacy xxxhdpi icon and an adaptive icon should be  192x192 pixels.

**Comment by anonymous73** [comment]
Thanks Bill. That means, Taco, the resource about adaptive icons that you provided might be too up to date?  The resource that you provided says adaptive icons are 108x108, but maybe to be backward compatible it should be 192x192? Taco you might want to look further into this. 

Yes. Bill there are some details in the original icon. Unfortunately not all of them can be appreciated at a small size, but I do like the subtle gradient on the page so I added that. When I did this icon I did want to stay true to the original vision. I just wanted to bring it out more.

You wanted 512? Say no more, fine sir. :)

**Comment by anonymous73** [comment]
Thanks Bill.

192 for adaptive?  Looks like that resource you posted, Taco, is a bit *too* up to date...

Yes there are some subtle details that I like like the gradient on the page, so I did just add that. When adding details to icons, I always try to make sure that they are noticeable at the small size. Basically the new one I made for editor is strongly influenced on your original design so as not to cause confusion. 

You need 512x512? Say no more, fine sir. :)

**Comment by anonymous73** [comment]
Trying to attached the png. Maybe attaching files no longer works over Tor. :(

**Comment by anonymous73** [comment]
It looks like the page no longer supports Tor Browser. If anyone knows a sore where I can host the icons that is Tor friendly tell me, because I have just looked,  there seems to be none on the clearnet.

**Comment by anonymous73** [comment]
**site** where I can host **images**, rather.

**Comment by TacoTheDank** [comment]
@anonymous73 I found these: 
https://www.reddit.com/r/onions/comments/49x3jb/clearnet_image_host_eg_imgur_that_does_not_block/

https://torify.me/en/onion-rating/86-matrix-image-uploader.html

**Comment by anonymous73** [comment]
Thankyou DankTaco!!

The normal version of the updated icon:
http://matrixtxri745dfw.onion/neo/uploads/190317/MATRIX_035153_rlj_Editor512-v3.png

**Comment by anonymous73** [comment]
The retro version (please note that in order to visit these onion links you will need the Tor browser and the site says that the images will exist on the site for a minimum of 30 days.):
http://matrixtxri745dfw.onion/neo/uploads/190317/MATRIX_040120_BVJ_Editor512-v3retro.png

If someone wants to repost the icons into this issue thread then that may be helpful.

**Comment by TacoTheDank** [comment]
May I ask why you don't just use something like Imgur? Seems like a lot of hassle that could be easily averted. :/

**Comment by anonymous73** [comment]
Hello Dear Taco,

Yes. Many clearnet services discriminate against well-meaning Tor users. Normally it's not the website's fault, they simply rely on Big Data companies like Google to handle security, that have alterior motives for want more information from people.

I have decided to upload the plain svg file to pastebin. Please tell me if you can now enjoy the icon in high resolution, Bill and Taco. Copy the pastebin contents to a txt file. Then convert that file to svg et voilà.

The normal icon:
https://pastebin.com/t0CStJCC

The retro themed icon will be paste-binned if Bill likes this normal icon and is interested in updating the icon.

I hope you both really like it. If you have suggestions please provide them!

**Comment by anonymous73** [comment]
Dear Bill, the above is also for you to read.

**Comment by anonymous73** [comment]
Dear Bill,

I realise that you don't attach much importance to the icon bit many people do. Many people want **everything** to look nice and just work. That is why Apple has become so popular. It is common for people to turn away from free and open-source because it often failed in these areas too. What I want is for FOSS to start to compete with the proprietary on the basis of providing better user experiences.

Icons are important because they are things that people look at multiple times everyday.

**Comment by TacoTheDank** [comment]
I often find that the apps in the Play Store and F-Droid that I find myself more likely to contribute to and use are the apps that have pleasing-to-the-eye icons. Adaptive can play a big role in that lol.

Here's the icon @anonymous73 posted:
![image](https://user-images.githubusercontent.com/32376686/55281329-09753c80-5309-11e9-98b4-5549f37f7a28.png)

**Comment by anonymous73** [comment]
Thanks DankTaco, and thanks for posting it up for me.
 
It appears that Bill has been busy developing features but hopefully he will make his intentions known soon. In the meantime if anyone sees and really likes  the icon. Feel free to create a pull request.

**Comment by mvbasov** [comment]
Dear Bill,
Don't change your nice application icon. IMHO.

**Comment by anonymous73** [comment]
Hi mvbasov,

Yes the idea of adaptive icons, for a parallax effect was introduced by DankTaco above, who provided links to documentation. Bill also had further knowledge on pixel widths of these icons for legacy systems. Which compelled me to upload the svg, so he or whoever, can size the icon properly for the different phones.

What idea do you have for a parallax effect?

After some consideration I decided against developing an adaptive/parallax icon. Because although the pencil could be a foreground element the shadow touches not only the corner edge of the pencil but the edge of the paper too. So we cannot simply put the shadow in the foreground. What I *could* do is make the background image the paper itself and allow the different Androids OSes to crop the paper however they wish. Ie. circle shape, squircle shape or rounded square. I might do a different background design for each so the writing on the page conforms to either a circle, squircle, or rounded square, ie, whichever icon type is chosen by the OS?

If you prefer Bill's design, can you tell me what you prefer so I can improve my design for you? Maybe you like the idea I am suggesting above, Mvbasov?

Hi Bill, what do you think of my above idea for a parallax/adaptive icon design? 

Dear Bill, earlier you said that once you decide on an icon you tend not to change it, but many icons change and improve. Here is a link to apkmirror showing the tacky old version of the Firefox logo from only two years ago, I forgot how much of an improvement the icon was at the time. Here's the link:
 www.apkmirror.com/uploads/page/2/?q=firefox

From Septmber to November 2017 just look at the improvement! It's night and day.

So many icons have improved over the years, remember the tacky Tor Browser icon, it changed only a few months ago and is a lot better. Icons should change to reflect people's expectations, while staying true to the original in some way. I think I have been able to achive that. If you want more gradient coloring on my design I can do that also, I thought the gradient that I added to the page was dynamic enough but I can do more. Please tell me how you want it improved.

Thanks for your consideration everyone.
