### ISSUE TITLE
[Request] Set Home Folder and Black Theme

### ISSUE THREAD

**Issue by iknownothingaboutcomputers** [billthefarmer/editor#7]
Currently Editor remembers the folder of the file last opened. It'd be nice if, for example, one could just set 'Documents' as Home.

Black theme would be even better than dark theme.

Thank you.

**Comment by billthefarmer** [comment]
Editor doesn't remember, the file picker does. If you have a file manager installed, you get a choice. The dark theme is the standard android Material or Holo theme. I don't make my apps any more complicated than they need to be to get the job done.
