### ISSUE TITLE
.MD-files greyed out.

### ISSUE THREAD

**Issue by NitroNils** [billthefarmer/editor#71]
I was so excited to see a new update, I've been a fan for years!
Tried to find a changelog (failed) and read it could open markdown in a browser!

So I tried opening .md-files, but they were greyed out (using the built-in framework).

Is it so that we can write md's, but not open them?

**how to open md?**

`Android 6.1`
`Huawei p8 Lite`

**Comment by billthefarmer** [comment]
The built in file picker/file manager is part of android, not the app. See #60, #45. Unfortunately it doesn't think .md files are text files. If you install a different file manager such as [OI File Manager](https://f-droid.org/en/packages/org.openintents.filemanager), it will let you open any sort of file.

**Comment by NitroNils** [comment]
Thank you, that makes it clear.

And your tip did not fool me into installing a bloated file browser,
but promted me to import .md via the superior [Ghost Commander,
dual-pane file manager](https://f-droid.org/app/com.ghostsq.commander)
- it worked perfectly!

**Comment by billthefarmer** [comment]
Well that's interesting. The reason it's not as bloated is because they use proguard to compress it. I used to use Norton Commander back in the DOS days when it was about the only thing available.

**Comment by NitroNils** [comment]
Oh, is that common?
It should be, I suppose!

The mother of two-pane! Norton.

I've fiddled with Midnight Commander on workstation. Ranger too.
Next up is the ed(1)-based one (as well as edbrowse a web browser w/
ed-interface (js-included).

ed(1) and editor are my two fav ones.

Enjoy the farming😃
