### ISSUE TITLE
Function improvement

### ISSUE THREAD

**Issue by kenneth-Q** [billthefarmer/editor#73]
Thanks for your editor software.
I have an idea to improve user experience. Use icon to highlight the parent file. That like:
![Editor-chooser](https://user-images.githubusercontent.com/11911577/57072193-736d7100-6d0f-11e9-9c28-05b2e1943429.png)
I have no idea to modify the code because I am a noob. :)
I cannot to check if the file is parent file.
>            if (file.isDirectory())
>            {
>                if (file.getPath()
>                    .equals(Environment
>                            .getExternalStorageDirectory().getPath()))
>                    name.setCompoundDrawablesWithIntrinsicBounds(externalId,
>                                                                 0, 0, 0);
>                else
>                    name.setCompoundDrawablesWithIntrinsicBounds(folderId,
>                                                                 0, 0, 0);
>            }
I changed any things, I hope these are useful for you.

[editor.zip](https://github.com/billthefarmer/editor/files/3137835/editor.zip)

**Comment by billthefarmer** [comment]
That is in the latest version, I used the sd storage icon

![ic_action_sd_storage](https://user-images.githubusercontent.com/3448386/57073191-3e91f780-6cd8-11e9-8f0c-09ea5f45194a.png)

**Comment by kenneth-Q** [comment]
Emmmm..
I think:
![Screenshot_2019-05-02-19-49-45-1](https://user-images.githubusercontent.com/11911577/57073724-8a629200-6d14-11e9-8707-3d767fdba273.jpg)

**Comment by kenneth-Q** [comment]
Oh, how did you draw these beautiful icons？
### If you have download my zip file, you can find my ugly icon. :P
I have a lot of things to learn. :D

**Comment by billthefarmer** [comment]
There is a complete set of icons on the [Material Design page](https://material.io/tools/icons/?style=baseline). I use older ones. I have attempted to add your suggestion, but I can't get the code to work.

**Comment by kenneth-Q** [comment]
I got an error. Install package from F-droid but I got this error:
> App not installed. An existing package by the same name with a conflicting signature.

Pls fix it. Or may I install the old one?
Thanks.

**Comment by billthefarmer** [comment]
If you built it and installed it yourself you must uninstall it before the version from f-droid will install. You can do that in f-droid, settings or using the launcher.

**Comment by kenneth-Q** [comment]
I choose update the package. From v1.34 update to v1.35.These two version were downloaded from F-droid.

**Comment by kenneth-Q** [comment]
I am sorry. I cannot run this version.
Android 5.1

**Comment by billthefarmer** [comment]
I can't reproduce this on the devices I have, I shall have to test it on an emulator.

**Comment by billthefarmer** [comment]
OK, android 4 and 5 don't like regex `\R` linebreak, undocumented in [Pattern](https://developer.android.com/reference/java/util/regex/Pattern#summary-of-regular-expression-constructs) docs. Fixed in the next version together with #76.

**Comment by kenneth-Q** [comment]
Thanks. This has been fixed.
