### ISSUE TITLE
Would you support .md files

### ISSUE THREAD

**Issue by ivysrono** [billthefarmer/editor#74]
just edit as .txt

**Comment by billthefarmer** [comment]
From version 1.33 the built in file chooser will open any file which android doesn't think is a media file or is too large. External file managers are all different. It's not possible to deal with the foibles of all of them.

**Comment by ivysrono** [comment]
thanks，file chooser think my file is too large. The limit is 250kB?

**Comment by ivysrono** [comment]
would you add an opinion to disable the size limit？

**Comment by billthefarmer** [comment]
Large files also make the app extremely sluggish and unresponsive.

**Comment by billthefarmer** [comment]
If you want to override the size limit, use a file manager to open the file. However the editor app may crash or stop responding when attempting to deal with a large file.

**Comment by ivysrono** [comment]
thanks

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
#45
