### ISSUE TITLE
adding data/timestamp to text

### ISSUE THREAD

**Issue by tengucrow** [billthefarmer/editor#75]
It would be very convenient to be able to insert in the text data/time stamp in user defined format (like strftime lib).

**Comment by billthefarmer** [comment]
There is no [strftime](https://en.cppreference.com/w/c/chrono/strftime) in android Java, but there is [SimpleDateFormat](https://developer.android.com/reference/java/text/SimpleDateFormat), which has a similar set of format characters. It would be possible to define a date template, such as `{{<EEE, d MMM yyyy HH:mm:ss>}}`, which would appear as `Wed, 4 Jul 2001 12:08:56`. However whatever enclosing delimiters are chosen, there is likely to be a conflict with something. For example, the delimiters I have used here are used for Hugo shortcodes.

**Comment by tengucrow** [comment]
I rather thought about menu item like "insert datastamp here" with ability change its format somewhere in app properties. When use editor as daily journal or lifelog it may be useful feature imho.

**Comment by billthefarmer** [comment]
In that case, consider using my [Diary](https://github.com/billthefarmer/diary) app which already has that feature and can also be used as a journal, and can have images, media, maps, etc. This app already has too many menu entries and I don't want to add settings as well.
