### ISSUE TITLE
Suggstion check box inverted.

### ISSUE THREAD

**Issue by mvbasov** [billthefarmer/editor#76]
Editor version 1.35.
Installed from F-Droid.
Device Xiaomi Mi8.
Android 9
Firmware: LineageOS 16.0-20190509-NIGHTLY-dipper

Steps to reproduce:
1. Open Editor.
2. Set settings check box for "Suggestion" marked.
3. Close Editor.
4. Open file from another application (X-Plore, OMN) by the Editor
5. Enter to edit mode by tapping pencil icon

At this state I expect suggestion above keyboard at typing time.
There is no suggestion.
If open settings suggestion check box marked. 
If tap this check box twice - suggestion appear.

But, if leave sugggestion settings disabled (check box not marked) and don't touch the settings next time input suggestion operate...

Another words explanation: suggestion settings stored in inverted state but if changed during edit session operate corresponding tick mark till session closed.

**Comment by mvbasov** [comment]
May be (NOT CHECKED!!!!)
Editor.java:onCreate() (416 line)
...
else if (!suggest)
...
need to be:
else if (suggest)

**Comment by mvbasov** [comment]
I think, I've found the problem:
Editor.java:setListeners()(line 549):
```
               // Set editable with or without suggestions
                if (!suggest)
                    textView
                    .setInputType(InputType.TYPE_CLASS_TEXT |
                                  InputType.TYPE_TEXT_FLAG_MULTI_LINE);
                else
                    textView
                    .setInputType(InputType.TYPE_CLASS_TEXT |
                                  InputType.TYPE_TEXT_FLAG_MULTI_LINE |
                                  InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);
```
`if (!suggest)` need to be changed to `if (suggest)`

I can perform local test build and make pull request, if you wish.

**Comment by mvbasov** [comment]
You have so easy readable code. Thank you!
Keep it in the same state, please.

**Comment by mvbasov** [comment]
Local version compiled.
Fix checked. (963 line affected also)
Pull request created.

**Comment by mvbasov** [comment]
1.36 version fix issue. (my build from your source)
P.S. Release 1.36 doesn't contain prebuild apk assert. Add it please.
P.P.S Who need to close issue? You or I? What are rules?

**Comment by billthefarmer** [comment]
I'm not sure what you mean by 'prebuild apk assert'. If you mean the built app apk, all my apps are built by F-Droid on their secure build system with their signature and when they put the latest apk up on their web site, I upload it here. That way if someone downloads and installs from here they can still upgrade via F-Droid. It doesn't matter who closes the issue, sometimes the person who opened it does or I do after a week or so if the originator doesn't.

**Comment by mvbasov** [comment]
It is a good idea to put F-Droid build apk to github assets! I will do the same for my projects.
