### ISSUE TITLE
Google playmarket version by Globetech

### ISSUE THREAD

**Issue by mvbasov** [billthefarmer/editor#78]
I think, the Globetech company stolen your sorce and made its own application based on its. The interface and functionality very very similar.
They put very annoying advertising to his application.
They didn't mention your work and it is license violation because you code has GPL license. [Link to mentioned programm](https://play.google.com/store/apps/details?id=com.globetech.maxtexteditor).

If you don't interesting this informationc close this issue, please, and sorry for disrurb.

**Comment by kenneth-Q** [comment]
wtf? What company it is?

**Comment by billthefarmer** [comment]
Thank you, I shall report it.

**Comment by mvbasov** [comment]
The mentioned application doesn't exists in the market now. Issue need to be closed :)
