### ISSUE TITLE
Add “Image icon" and “Background Theme" in this app.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [billthefarmer/editor#79]
#### Proposal:
My suggestion is about to add “Image icon" and “Background change" feature to this app. Which will result in the better note making and note editing.
#### Mockups/Examples:
* Addition of Image Icon:
![PicsArt_05-16-03 37 00](https://user-images.githubusercontent.com/37048415/57846451-da038c00-77f1-11e9-8c90-2bd351c642b3.png)
* Addition of “Background Theme" changer:
![PicsArt_05-16-03 38 00](https://user-images.githubusercontent.com/37048415/57846556-20f18180-77f2-11e9-81bf-8362d1a83d10.png)
* After implementation of both features:
![PicsArt_05-16-03 44 55](https://user-images.githubusercontent.com/37048415/57846401-c2c49e80-77f1-11e9-9306-58374d71661c.png)
#### Benefits:
Benefits of implementing these two features are as under:
* Benefit of adding “Image Icon" is that while making or editing note or text file a user can add image to the note or text file. As we all know that Text files of Notes are using more than any other source. If a user wants to add some image in his note or text he can add through this feature. This feature can make  notes of text files better look than before.
* Another is “Background Theme" changing, its benefit is that a user who is writing a text file or note can change the background theme or simple a user can edit the whole note or text file in that very theme, which results in the best format of the note. 
Simply i will tell you that by this feature a user can bring his whole note in a beautiful template.

**Comment by billthefarmer** [comment]
Very nice, but this is a text editor, not a word processor or web page editor. It is not possible to include images in a text file unless it is an HTML or Markdown file, in which case the images are references to external files, are not included in the text file and would need to be displayed in another app.

**Comment by PeerzadaZeeshan** [comment]
@billthefarmer yes i know this is a text editor, but if a user need to add image to that text file what he will do for that.
Same for the background change feature...

**Comment by billthefarmer** [comment]
OK, please explain how to include an image in a text file that can be edited with a text editor like notepad on a PC, or vim on Linux.

**Comment by PeerzadaZeeshan** [comment]
Let me tell you have you used any notes app...
Just like the notes app in which user can edit his note and add image into it.
Same is the case with here...... User can edit text file and add image in it if needed....

**Comment by billthefarmer** [comment]
You clearly didn't note: **"a text file that can be edited with a text editor like notepad on a PC, or vim on Linux"**.

**Comment by PeerzadaZeeshan** [comment]
So acc.to you we cannot add image to txt file..... Right??

**Comment by billthefarmer** [comment]
You clearly didn't note: **"It is not possible to include images in a text file unless it is an HTML or Markdown file, in which case the images are references to external files, are not included in the text file and would need to be displayed in another app"**.

**Comment by PeerzadaZeeshan** [comment]
Ok i got it.....
But what about the Background Theme changer.....?

**Comment by billthefarmer** [comment]
The app already has three themes and does syntax highlighting of source code files, which would be hard to read against a background image. If you want an app that can do all these things except the source code highlighting, consider my [Diary](https://github.com/billthefarmer/diary) app.

**Comment by PeerzadaZeeshan** [comment]
Ok thank you....

**Comment by gilcot** [comment]
Oh I see... @PeerzadaZeeshan thought it's a "notes taker" (a kind of pesonal wiki app or thing like _Evernote_ and alike) and he's not used with simple "text editor". That's maybe 'cause some people use to call the previous "notes editor" (too much things are called editors and many people think they can "edit" anything without the right tool ; thanks _μ$ 0ffice_ for spreading confusions)
