### ISSUE TITLE
Add “Favourite" feature and “Language" feature in the app.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [billthefarmer/editor#80]
#### Proposal:
This suggestion is about to implement Favourite feature and Language feature in the app. 
#### Mockups/Examples:
Adding favourite option within file:
![PicsArt_05-19-12 14 11](https://user-images.githubusercontent.com/37048415/57978718-10c6e580-7a30-11e9-90c7-8c5c3095109d.png)
Then the favourite file marked will go to this option where we can see them later:
![PicsArt_05-19-12 10 38](https://user-images.githubusercontent.com/37048415/57978728-33f19500-7a30-11e9-9f48-01a585b48f1e.png)
Adding **Language** feature to the app:
![PicsArt_05-19-12 12 41](https://user-images.githubusercontent.com/37048415/57978733-4b308280-7a30-11e9-9d27-d9452c24fab5.png)

#### Benefits:
The benefits of implementing these two features are as under:
* By implementing **favourite** option to the app, a user can mark any of his file in favourite list which he can use later by simply going to this option and find that file. This feature can save a lot of time for user and can easy his work. In simple word, user don't have to find the file in his file manager which will take a lot of time for him.
* Now by implementing **Language** feature, user can use the app in many languages. As we all know that there are many languages in this globe and many user are not comfortable with english language. So this feature can help user to feel comfort with his mother language.

**Comment by billthefarmer** [comment]
This is a **text** editor, not a diary, journal, blog, etc. It already has a open recent file option 
and has been translated into 12 languages. As suggested before, if you want this sort of functionality, try my [Diary](https://github.com/billthefarmer/diary) app.

![Screenshot_20190519-083527 1](https://user-images.githubusercontent.com/3448386/57979137-2678e280-7a11-11e9-8533-80e6d6f71999.png)

**Comment by PeerzadaZeeshan** [comment]
I am not saying that....
I want to say that whole language of the app should be changed..
And by recent files user can open only those files which he had used recently but favourite option he can mark the file which he hadn't recently used....
