### ISSUE TITLE
Saving the default Editor.txt file overwrites any previous Editor.txt file without warning.

### ISSUE THREAD

**Issue by hyphenrf** [billthefarmer/editor#81]
Issue: the title
Desired behaviour: warning the user before overwriting anything
How to reproduce: Open a new file, write something, save as Editor.txt, now open the app on a blank Editor.txt and save, old one gets overwritten.

**Comment by billthefarmer** [comment]
I'm not sure how you managed to do that. The default behaviour is to open Editor.txt if it exists, so if you blank it out and save, it will get overwritten as should happen.

**Comment by hyphenrf** [comment]
I understand that, and I think I blanked the Editor.txt file out myself because I thought I was opening a cached buffer not the saved file. 
What I'm trying to point out is that there are no overwriting warnings in general. Many mistakes like mine could be avoided with a simple overwrite warning. Additionally, I could have /sdcard/Editor.txt and /sdcard/Documents/Editor.txt and they will both show on the app interface as Editor.txt which could add a layer of ambiguity.

**Comment by billthefarmer** [comment]
It is not normal practice for an editor to give a warning if you load a file, modify it, and then save it. That's what it's supposed to do. You will get a warning if the file has changed in storage while you were editing it.

The default file behaviour is documented in the [README](https://github.com/billthefarmer/editor#default-file).

**Comment by gilcot** [comment]
Hello,

It would be unproductive if I'm warned everytime I save a modification... 

But what isn't clear is whether the original content is loaded (so you already know you are changing that file) or if you just have a blank page on opening (in such a case I agree it's buggy behaviour)

**Comment by billthefarmer** [comment]
The README says:
> If there is no open file any text entered will by default be saved in
`Documents/Editor.txt`. This file will be loaded on start if it
exists. Use the `Save as` menu item to save it elsewhere.

If there is no default file, you will get a blank page which will become the default file if you save it.
