### ISSUE TITLE
no message when not saving

### ISSUE THREAD

**Issue by nikoss** [billthefarmer/editor#82]
Steps to reproduce:
- with the help of F-droid, download and install "File Manager"
(https://gitlab.com/axet/android-file-manager)
- using "File Manager", click on a .txt file
- choose to open with Editor
- File Manager will open Editor "externally", probably not granting permissions or something like that
- make some changes on the file
- click the save icon
- the icon will animate
- but the changes have not been saves
- no message or indication of that, or why it was not saved
- yet, the user might be under the impression that the file was saved

My system is...
- Android 7
- Editor 1.36
- File Manager v0.2.94

**Comment by billthefarmer** [comment]
The foibles of various file managers is why I added a file picker to this app. This one produces yet another weird content Uri...
```
intent://com.github.axet.filemanager/72c42b5ee52a0b5b991a0fd486d3e88a/Editor.txt#Intent;scheme=content;type=text/plain;launchFlags=0x33000000;end 
------------ 
ACTION: android.intent.action.VIEW 
DATA: content://com.github.axet.filemanager/72c42b5ee52a0b5b991a0fd486d3e88a/Editor.txt 
MIME: text/plain 
URI: intent://com.github.axet.filemanager/72c42b5ee52a0b5b991a0fd486d3e88a/Editor.txt#Intent;scheme=content;type=text/plain;launchFlags=0x33000000;end 
FLAGS: 
FLAG_RECEIVER_REPLACE_PENDING 
FLAG_ACTIVITY_FORWARD_RESULT 
FLAG_ACTIVITY_PREVIOUS_IS_TOP 
FLAG_RECEIVER_FOREGROUND 

------------ 
MATCHING ACTIVITIES: 
HTML Viewer (com.android.htmlviewer - com.android.htmlviewer.HTMLViewerActivity) 
FBReader (com.fbreader - com.fbreader.android.fbreader.FBReader) 
NAVIGON (com.navigon.navigator_checkout_eu40 - com.navigon.navigator_select.hmi.CheckRegistrationActivity) 
Diary (org.billthefarmer.diary - org.billthefarmer.diary.Editor) 
Editor (org.billthefarmer.editor - org.billthefarmer.editor.Editor) 
Firefox (org.mozilla.firefox - org.mozilla.firefox.App) 
Save as (org.openintents.filemanager - org.openintents.filemanager.SaveAsActivity) 
```
I have added an alert dialog if saving a file fails, which will be in the next version.

**Comment by nikoss** [comment]
I tested it again with Editor version 1.38 
(File Manager and Android versions still the same).
A pop up appeared, 
warning of ...
"Permission Denial: blah blah"

Looks fixed to me!
