### ISSUE TITLE
more themes? 

### ISSUE THREAD

**Issue by gilcot** [billthefarmer/editor#84]
Currently, they're three themes (foreground on backgroud, comment):
  - light (black on whity/very-light-gray/ivory, like currently seen with most word processors nowadays)
  - dark (white on blacky/very-dark-gray, like currently seen with many terminals/tty-emulators nowzdays)
  - retro (green on black, like old CRT display I worked on with visicalc and laterly popularised by Matrix movie)

Well, what about adding more oldy themes?
  - retro-blue (whity on dark-blue, like DOS users were used with [Turbo Pascal IDE](https://lite.qwant.com/?q=turbo%20pascal&t=images) and some other editors' [screen](https://commons.m.wikimedia.org/wiki/File:Turbo_Pascal_7.0_Scrren.png#mw-jump-to-license))
  - retro-c64 (lavender on dark-blue, with possibly bolder font like with [Commodore 64C](https://commons.m.wikimedia.org/wiki/File:C64c_system.jpg#mw-jump-to-license) [familly](http://1amstudios.com/2016/11/27/c64-slack-client/))
  - retro-gray (black on light-gray, like DOS users were used with [QBasic IDE](https://archive.org/details/msdos_qbasic_megapack#loading) [formerly](https://en.m.wikipedia.org/wiki/File:QBasic_Opening_Screen.png#mw-jump-to-license) and alike)
  - commander (yellow on blue, like MC... even if [panels](https://www.gnu.org/software/mc/images/mc-panels.png) are mainly in white, the [editor](https://www.gnu.org/software/mc/images/mc-edit-perl.png) favors yellow like many [PiCo integrated editor](https://www.brighthub.com/computing/linux/articles/39511.aspx)...) 
  - retro-amber ([between-yellow-and-orange](https://en.wikipedia.org/wiki/Amber_%28color%29) on black, another vintage seen on CRT too..)
  - night-[neon](https://commons.m.wikimedia.org/wiki/File:AC_powered_NE-2_type_neon_lamp_close-up.jpg#mw-jump-to-license) (red on black, just because it's very nice to have that too)
  - pink-panther (pinky on purple, for the [fun](https://en.wikipedia.org/wiki/The_Pink_Panther) and should have very little code colours)
  - retro-green (green on black, renaming to distinguish from other retro...)

The two cents of an old boy :)

**Comment by billthefarmer** [comment]
The colours I used for syntax highlighting show up reasonably well on all three themes and work best on the retro theme. I don't think that would work with more theme colours. Also this app is already too complicated for a simple text editor and the menu has already got too many entries. And people keep asking for all sorts of [bizarre stuff](https://github.com/billthefarmer/editor/issues/79) like embedded images and background images, and [more](https://github.com/billthefarmer/editor/issues/80). And I thought I was bonkers!

**Comment by gilcot** [comment]
Hello Bill,

I didn't know (and didn't try enough to notice) that all themes share the same syntax highlighting colors. (so I agree it won't fit everywhere...) And was preparing the table of other related colors for each theme if you'd agree with the idea. 

Another way to deal with that question is making a menu where everyone can set they preferences, but it implies some refactoring I guess. The theme menu entry will become then: 

| default background | selector |
| default foregroung | selector |
| keyword1 foreground | selector |
| keyword2 foregroung | selector |
| keyword3 foregroung | selector |
| variable foreground | selector |
| string foregroung | selector |
| number foregroung | selector |
| comment foregroung | selector |
| search backgroung | selector |

n.b.: With [_curl_ example `chkspeed.c`](https://curl.haxx.se/libcurl/c/chkspeed.html), a keyword1 is `static` or `if`, a keyword2 is `char` or `int`, a keyword3 is `long`, a keyword4 is `WriteCallback` or `CURLcode`, etc.

The selector may be, for example, a drop-down list of [eight console colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) or a ([safe color](https://en.wikipedia.org/wiki/Web_colors#Web-safe_colors)) [wheel picker](https://android-arsenal.com/tag/18) (well, [according to a _SO_ comment, one can use Inyents](https://stackoverflow.com/a/2442743)...) 

I dunno if there's a simple way to archive that. Unfortunately I don't know enough Java and not at all Android SDK, otherwise I should work on it and submit for review and merge :(

p.s.: I didn't know [that word](https://www.urbandictionary.com/define.php?term=bonkers) I undersrand [bothered](https://www.merriam-webster.com/dictionary/bonkers) isn't it? :)

**Comment by billthefarmer** [comment]
Far too complicated and far too many menu entries. The green on black retro theme I picked is because it was fairly universal - ATMs screens you could read in bright sunlight, mainframe terminals, oscilloscopes, monitors for very early home and breadboard computers before the colour ones, early calculators, etc.

**Comment by gilcot** [comment]
Thanks for your reply.
