### ISSUE TITLE
Hard to search and edit in multi pages document

### ISSUE THREAD

**Issue by mmm4m5m** [billthefarmer/editor#85]
Try to search and edit in multi pages text document. 

For example 5 pages (screens) document. Every page have word "invalid". Try to search "invalid", to delete it and type "valid".

I think, when search start, it is not in edit mode anymore. Also the moment I press "delete" to delete the word it also delete content of search box and cursor jumps to the first line.

Thanks.

**Comment by billthefarmer** [comment]
There are several relevant points: This app is just a simple wrapper around the built in android [EditText](https://developer.android.com/reference/android/widget/EditText) and [SearchView](https://developer.android.com/reference/android/widget/SearchView) functionality, intended for editing small text files. The highlighting done by the search function is not a selection as the search works the same way in both view and edit modes. Android clears the search view if you move the focus and start typing in another view.

It is possible to put the search text back after it has been cleared, as I have done in another app, but this doesn't help in this case as it just goes back to the first match.

**Comment by billthefarmer** [comment]
After some investigation I have added code to put the search text back, which makes it possible to do a search and replace. You need to select and copy the replacement text first, possibly by typing it into the search field. Then type in the search text, the first match will be highlighted, double tap or long touch on it to select it, and paste from the pop up menu. The search text will be put back and the highlight will move to the next match.
