### ISSUE TITLE
Fallback "generic" syntax highlighting

### ISSUE THREAD

**Issue by ClockGen** [billthefarmer/editor#86]
Hello, I've noticed there's a new "syntax highlight" feature, is it possible to add some sort of "fallback" highlighting for not supported languages?

**Comment by billthefarmer** [comment]
The default highlighting is for C type languages that share a mostly common set of keywords and conventions. I think I've covered all those I know of in common current use. Languages that use different conventions or keywords aren't going to work. Bear in mind that this is a simple editor intended for use on an android device. I wouldn't use it for anything other than viewing or editing small config files or scripts.

**Comment by ClockGen** [comment]
Still, I stopped on your editor since it seems to be the fastest one - many editors in f-droid have troubles opening large files, while in your editor I can comfortably view, edit and do other operations on large files (300-500 kb and bigger).
By "falback" highlighting I meant highlighting only various reserved words, or maybe operators like =, ~, etc. For example turbo editor (in f-droid) does exactly that, instead of having a separate scheme for each language.

**Comment by billthefarmer** [comment]
OK, I have released a new version with default highlighting for unrecognised extensions. It does not highlight comments as there is little consistency of comment delimiters outside C type languages.

**Comment by ClockGen** [comment]
Wow, very fast. Thank you very much, works exactly like I had it in mind.
