### ISSUE TITLE
File size limit in file selection dialogue?

### ISSUE THREAD

**Issue by sokolgeo** [billthefarmer/editor#89]
I have a text file, which I am unable to select in Editor to open and edit. In file list the name of this file is in dark-grey colour and I could not choose it for editing. 

Funny enough, if I call Editor from file manager to edit the very same file, Editor opens this file and allows me to edit it.

The only thing I could see special is that my file is ~300 kb size. Other my files are similar, just smaller file size than 300 kb.

Is there file size limitation hardcoded into the Editor? Does it have to be there?

**Comment by billthefarmer** [comment]
There is a file size limit of 256Kb in the file select dialog. This is because the editor stores all the file in memory and becomes unresponsive and difficult to use editing large files. It was intended as a simple editor for config files and short scripts, and never as a source file editor or document editor.

It's easy to get around it, as you have found, by using a file manager, but this is unsupported.

**Comment by sokolgeo** [comment]
OK, thank you for clarification

**Comment by clach04** [comment]
I have no problem with the file size limit, I'd like to confirm what it is. It looks like as of today limit is ~500Kb from a quick code scan https://github.com/billthefarmer/editor/blob/89876eb516dab5518f59a17280c3b91cbb26cbe9/src/main/java/org/billthefarmer/editor/FileAdapter.java#L52 (so a little larger than in [2019](https://github.com/billthefarmer/editor/issues/89#issuecomment-544132202) )

Thanks for making this to available!

**Comment by billthefarmer** [comment]
I increased it, based on the performance of my Moto G (3G). If and when 3G gets phased out older phones will become plastic bricks and I may increase it again. Bear in mind users of FOSS apps probably tend to use older cheaper kit.

**Comment by seniordevel** [comment]
Hello, I have same problem, I tried to open a spell dictionary, about of 8 MB in size, but was not accepted by your Editor. It was opened from filemanager.

I see that clatch04 wrote patch, sent a pull request and you already merged it.

Will this fix my problem (I need 8 MB) ?

**Comment by clach04** [comment]
@seniordevel no 8Mb is NOT supported (and likely not to be). My patch in https://github.com/billthefarmer/editor/commit/fb348d5a4608855816ab6d9d73ab4e5004abd02d is to document the limit so it is clearer to end users in the readme.

You do have the option of changing this value on your machine and rebuilding (and testing), but my understanding is that https://github.com/billthefarmer/editor is not intended for large editing tasks.
