### ISSUE TITLE
Add setting to opening file for editing

### ISSUE THREAD

**Issue by sokolgeo** [billthefarmer/editor#91]
This is to resurrect #25 and offer may be better approach: add one more option, like "edit opened files by default". It will be mighty handy since I only open my files for editing and clicking "Edit" icon each time is kind of dumb for the program called "Editor", not "Viewer".

Could you please consider adding "Open files for editing" option? Thank you.

**Comment by billthefarmer** [comment]
OK, I have released a new version with a `View files` option.

**Comment by sokolgeo** [comment]
Thank you! It should be compiled by F-droid soon, I assume?

Or I have to install the APK directly from Github?

**Comment by billthefarmer** [comment]
The app got built this morning by F-droid, so it might appear on the F-droid app later today or tomorrow when they do an update. I will put it on Github when I can get it off the F-droid web site.

**Comment by sokolgeo** [comment]
Not on F-Droid so far, let's wait and see. Thank you again for looking
into this!

**Comment by sokolgeo** [comment]
So, new version updated on F-Droid. Well, I'd say it does not work
overall: with new setting the file is opened in edit mode. But neither
edit cursor not on-screen keyboard appear on screen. User has to click
on screen to get cursor and on-screen keyboard to actually start editing
the file. One would expect "open and start editing straignt away"
result, but not on my system. Could you please look into this, so edit
cursor and on-screen keyboard would appear automatically when in edit
mode? I am on Android 9. Thank you.

**Comment by billthefarmer** [comment]
That is intentional. The convention in all my apps and in general, I think, is that the keyboard doesn't appear until you select where you want to edit.

**Comment by sokolgeo** [comment]
With due respect, this looks like _worsening_ the initial workflow.

Before: long tap and start editing

Now: (1) set "edit by default" config option, (2) short tap to start editing


I am seriously looking into Markor text editor as better option for me
https://f-droid.org/en/packages/net.gsantner.markor/ :

+ no filesize limit or performance problems with files over 200kb

+ has undo function

+ can simply open file for editing by default, putting curson in the end
of the file and displaying on-screen keyboard - just what I need

- has no autosave. Can live without this one, I guess.

**Comment by billthefarmer** [comment]
The view files option is a setting - once you set it it stays that way. Or you can do it on a file by file basis using the mode line feature. [Mode line](https://github.com/billthefarmer/editor/blob/master/Mode.md).

**Comment by sokolgeo** [comment]
Yes, but this new option does not really change anything. User still has to click to start editing, when this new option is set. So what's the point of having this implementation of 'edit by default' if user still has to do extra click, just like before. Only before it was long tap and no hassle with one more setting. New implementation gives _worse_ user experience for my workflow.

Really - look at Markor - can edit by default and this gives user cursor in the end of file with onscreen keyboard displayed - as 'edit by default' should IMHO work. I believe they have extra option to put edit cursor in the beginning of file by default, but I'm happy with their default 'cursor in the end of file, onscreen keyboard displayed - ready to edit'

I guess the 1.43 Editor implementation would rather be dropped, but this is your show.
