### ISSUE TITLE
Add display & input tab key

### ISSUE THREAD

**Issue by kenneth-Q** [billthefarmer/editor#92]
We find the software cannot handle the tab(\t) on the text file(not a space). 
About the input way, we suggest to add a panel to input any symbool such as '{}$%&|~[]>=;:*"_' etc.
We hope it could be added. Thank you.

**Comment by billthefarmer** [comment]
I looked at this a while ago - #4. Even if you can find a keyboard which can input a tab character it won't appear in the file and the text view won't handle one already in the file. Best avoided.

**Comment by kenneth-Q** [comment]
Oh, I see. 😫
