### ISSUE TITLE
A small doubt about java 8 compilation

### ISSUE THREAD

**Issue by HemanthJabalpuri** [billthefarmer/editor#93]
@billthefarmer 

This is not a issue about your app. So I am closing this.

You app is simple, clean and uses Java 8 without any support libraries.

I am trying to build apps without gradle or ant.
So I am using aapt, dx, javac, jarsigner for this.

Generally we use android.jar as bootclasspath for compiling android java files upto Java 7.
But for compiling Java 8 language features like lamdas used in your app, we have to use rt.jar too for compiling.

This may lead to  compiling of unsupported API classes that are found in rt.jar but not in android.jar. Eg:- sun package classes.

Can you please tell a solution for this Sir.

I am not a developer to get a solution for this.

Here is a sample script for compiling apps without grade/ant.
https://github.com/HemanthJabalpuri/AndroidExplorer

Thanks

**Comment by billthefarmer** [comment]
My understanding is that the bootclasspath is telling the compiler what classes will be available at run time in the run time environment. Therefore they don't get compiled into the final jarfile/app, only referred to.

**Comment by HemanthJabalpuri** [comment]
> My understanding is that the bootclasspath is telling the compiler what classes will be available at run time in the run time environment. Therefore they don't get compiled into the final jarfile/app, only referred to.

@billthefarmer 
You are right.
But bootclasspath to android.jar ensures that we are only using API classes that are available at runtime.

But for compiling lamdas we need java.lang.invoke.LambaMetaFactory that is in rt.jar but not in android.jar.

So we have to use rt.jar for bootclasspath.

If we use rt.jar as bootclasspath, there may be use of API classes that are in rt.jar but not in android.jar.

Suppose let us import sun.misc.BASE64Encoder
it will not give error if we use rt.jar.
But will give error if you use android.jar

**Comment by billthefarmer** [comment]
Well as far as I can see, that's fine. The android docs tell you what classes are supported in android. If you put something in because you know it's in rt.jar then it might compile OK, but it won't run unless I'm missing something. Or the lint built into the gradle android build might pick it up, if you use it.
