### ISSUE TITLE
[Feature request] Clear recent files, undo/redo, root permissions

### ISSUE THREAD

**Issue by saalkom** [billthefarmer/editor#95]
Let me start off by saying I do understand and greatly appreciate the stance this project takes against feature-creep. That being said, I'd like to request a few small(?) enhancements that I think would do their part in improving the usability and utility of Editor for relatively little trade-off in terms of UI-bloat and resource-intensiveness.

1. There should be some facility to clear the recent file history. Presently the only way to do this is to clear the application data in App Info, which then requires that you re-adjust your settings back to how you like them when you reopen Editor. I would be content with an option at the bottom of the "Open recent" submenu, or a button at the top-right corner of said submenu, to clear the entire list, with or without user confirmation, but it may additionally be worth exploring the removal of individual history entries upon a swipe and/or long-press (preferably without a confirmation dialog box).

2. Undo and redo: self-explanatory, I think. To avoid menu-clutter, and because they will probably be used quite frequently, the buttons should go in the titlebar itself. That might be perceived as introducing titlebar/toolbar clutter, but this feature is so basic and generally expected that I think an exception should be made.

3. Root permissions: okay, I do understand if this one's too much of an ask. Sometimes, admittedly usually just for curiosity's sake, I wish I was able to view some of the myriad plaintext files that litter the areas of my internal storage that Editor doesn't have permission to read. I'm aware Editor uses the system filepicker, and it's fine if the system/in-app filepicker can't utilize any root permissions granted to Editor as a whole; I would just like to be able to open files in Editor using an external root file-manager app.

I hope you take my ideas into consideration.

**Comment by billthefarmer** [comment]
Clearing the recent file list is an omission I missed. That will be in the next version.

I have looked at undo and redo, android make it far too difficult, which is probably why it's not already in the built in UI. Implementing root access is also far too difficult.

Of course I am always open to someone cleverer than me having a go and putting in a pull request.

**Comment by saalkom** [comment]
That's all good. The unclearability of the recent documents list was my biggest pet peeve of these three anyway. If I were a programmer myself I would definitely try submitting a pull request. Maybe we should leave this issue open for a while until somebody does submit one?
