### ISSUE TITLE
[Feature request] Display an asterisk in the titlebar in front of the filename to indicate that there are unsaved changes to the currently-open file

### ISSUE THREAD

**Issue by saalkom** [billthefarmer/editor#96]
This would be useful for people who, like me, keep autosave turned off due to its destructive potential, and thus need to manually save.

**Comment by billthefarmer** [comment]
That's unnecessary because the save icon appears in the toolbar as soon as you make a change and if you attempt to discard an edited file by quitting the app or opening another file a dialog will appear asking if you want to save your changes.

**Comment by saalkom** [comment]
My mistake. I've never noticed that the save icon only appears when there are unsaved changes; I just thought it was always visible in edit mode. As for the save/discard dialog box, I virtually never see it because I exit all Android activiti
