### ISSUE TITLE
tab doesn't work

### ISSUE THREAD

**Issue by Sheolgorath** [billthefarmer/editor#98]
when I try to paste something with a tab or use the tab on my software-keyboard, nothing happens. If I paste formatted text it doesn't get deformatted and stays as example big.

**Comment by billthefarmer** [comment]
No it doesn't, see #92. The text view popup menu functions copy and paste are part of android and not part of the app. The text view supports text formatting, so any formatting gets copied along with the text. There's no paste without formatting in android. The formatting won't get saved in the text file when you save it.

**Comment by Sheolgorath** [comment]
well then. sorry for opening an issue regarding an issue which was already mentioned in an older issue.
