### ISSUE TITLE
False Chinese translation of "Clear list"

### ISSUE THREAD

**Issue by ShamrockLee** [billthefarmer/editor#99]
The label "Clear list" on the last button in the menu should be translated into "清空列表" (to clear/empty the list) instead of "清晰的列表" (a clear list). The latter will cause users to empty the list unintentionally.
![menu with the "清晰的列表" option in the bottom](https://user-images.githubusercontent.com/44064051/73136729-c51f0e00-408b-11ea-9bd9-696b6178a8df.jpg)

**Comment by billthefarmer** [comment]
Thank you. I have updated the app.
